'use client';

import React, { useState, useRef, useEffect } from 'react';
import QRScannerComponent from '@/src/components/qr-scanner';
import {
  ArrowLeft,
  CheckCircle2,
  RotateCcw,
  Trash2,
  Zap,
  Scan,
} from 'lucide-react';

// ---------------------------------------------------------------------------
// Types (aligned with rental-agreement page)
// ---------------------------------------------------------------------------

type RentalStatus = 'Active' | 'Completed' | 'Cancelled' | 'Pending';

interface ExpectedMachineCategory {
  id: string;
  brand: string;
  model: string;
  type: string;
  quantity: number;
}

interface RentalAgreement {
  id: number;
  agreementNo: string;
  customerNo: string;
  customerName: string;
  serialNo: string;
  startDate: string;
  endDate: string | null;
  monthlyRent: number;
  outstanding: number;
  status: RentalStatus;
  purchaseRequestId?: number;
  purchaseRequestNumber?: string;
  expectedMachines?: number;
  addedMachines?: number;
  expectedMachineCategories?: ExpectedMachineCategory[];
}

interface MachineForAgreement {
  id: string;
  description: string;
  serialNumber: string;
  boxNumber: string;
  brandName?: string;
  modelName?: string;
  typeName?: string;
  scannedAt?: string;
  categoryIndex?: number;
}

// Minimal invoice shape for auto-generated invoice (from rental-agreement)
interface AutoGeneratedInvoiceItem {
  id: string;
  itemCode: string;
  description: string;
  serialNumber?: string;
  brand: string;
  model: string;
  type: string;
  numberOfMachines: number;
  monthlyRentPerMachine: number;
  subtotal: number;
}
interface AutoGeneratedInvoice {
  invoiceNumber: string;
  customerName: string;
  customerAddress: string;
  vatTinNic: string;
  invoiceDate: string;
  periodFrom: string;
  periodTo: string;
  items: AutoGeneratedInvoiceItem[];
  subtotal: number;
  vatAmount: number;
  totalAmount: number;
  status: 'issued';
}

// ---------------------------------------------------------------------------
// Mock data (same Pending agreements as rental-agreement for consistency)
// ---------------------------------------------------------------------------

const mockCustomers = [
  { id: 'CUST-001', name: 'ABC Holdings (Pvt) Ltd', address: '123 Main Street, Colombo 05' },
  { id: 'CUST-002', name: 'John Perera', address: '456 Galle Road, Mount Lavinia' },
  { id: 'CUST-005', name: 'Mega Constructions', address: '654 High Level Road, Maharagama' },
  { id: 'CUST-006', name: 'VIHANGA SHADE STRUCTURES', address: '317/2, NEW KANDY ROAD, BIYAGAMA' },
];

const mockRentalAgreements: RentalAgreement[] = [
  {
    id: 2,
    agreementNo: 'RA24010002',
    customerNo: 'CUST-002',
    customerName: 'John Perera',
    serialNo: 'SN-2024-004',
    startDate: '2024-03-01',
    endDate: '2024-06-01',
    monthlyRent: 35000,
    outstanding: 70000,
    status: 'Pending',
    expectedMachines: 1,
    addedMachines: 0,
  },
  {
    id: 5,
    agreementNo: 'RA24010005',
    customerNo: 'CUST-005',
    customerName: 'Mega Constructions',
    serialNo: 'SN-2024-005',
    startDate: '2024-04-01',
    endDate: '2024-07-01',
    monthlyRent: 60000,
    outstanding: 180000,
    status: 'Pending',
    purchaseRequestId: 3,
    purchaseRequestNumber: 'PO24010003',
    expectedMachines: 15,
    addedMachines: 0,
    expectedMachineCategories: [
      { id: 'cat-5-1', brand: 'Juki', model: 'Model A', type: 'Industrial', quantity: 10 },
      { id: 'cat-5-2', brand: 'Juki', model: 'Model B', type: 'Industrial', quantity: 5 },
    ],
  },
  {
    id: 6,
    agreementNo: 'RA24010006',
    customerNo: 'CUST-006',
    customerName: 'VIHANGA SHADE STRUCTURES',
    serialNo: '2LIDH01733',
    startDate: '2026-01-02',
    endDate: '2026-08-01',
    monthlyRent: 17000,
    outstanding: 0,
    status: 'Pending',
    expectedMachines: 1,
    expectedMachineCategories: [
      { id: 'cat-6-1', brand: 'Juki', model: 'LK-1903A-SS', type: 'Electronic Bar Tack Machine', quantity: 1 },
    ],
  },
];

/** Get expected machine categories for an agreement. */
function getExpectedCategories(agreement: RentalAgreement | null): ExpectedMachineCategory[] {
  if (!agreement) return [];
  const cats = agreement.expectedMachineCategories;
  if (cats && cats.length > 0) return cats;
  const total = agreement.expectedMachines ?? 0;
  if (total <= 0) return [];
  return [{ id: 'default', brand: '', model: 'Machine', type: '', quantity: total }];
}

function findAgreementByNumber(agreementNo: string): RentalAgreement | undefined {
  const normalized = (agreementNo || '').trim().toUpperCase();
  if (!normalized) return undefined;
  return mockRentalAgreements.find(
    (a) =>
      a.agreementNo.toUpperCase() === normalized ||
      a.agreementNo.replace(/\s/g, '') === normalized.replace(/\s/g, '')
  );
}

/** QR contains only serial number and box number. Extract from JSON or key: value text. */
function extractSerialAndBoxFromQR(decodedText: string): { serial: string; box: string } | null {
  const raw = (decodedText || '').trim();
  if (!raw) return null;

  try {
    const parsed = JSON.parse(raw);
    if (parsed && typeof parsed === 'object') {
      const serialCandidates = [
        parsed.serialNo,
        parsed.serialNO,
        parsed.serial,
        parsed.serialNumber,
        parsed.SerialNo,
        parsed.Serial,
        parsed.machineSerial,
        parsed.machineSerialNo,
      ].filter((v: unknown) => typeof v === 'string' && (v as string).trim().length > 0);
      const boxCandidates = [
        parsed.motorBoxNo,
        parsed.boxNo,
        parsed.boxNumber,
        parsed.MotorBoxNo,
        parsed.BoxNo,
        parsed.box,
      ].filter((v: unknown) => typeof v === 'string' && (v as string).trim().length > 0);
      const serial = serialCandidates.length > 0 ? (serialCandidates[0] as string).trim() : '';
      const box = boxCandidates.length > 0 ? (boxCandidates[0] as string).trim() : '';
      if (serial || box) return { serial, box: box || '' };
    }
  } catch {
    // not JSON, try key: value pattern
  }

  const serialMatch = raw.match(/serial\s*(no|number)?\s*[:\-=]\s*([A-Za-z0-9\-_/]+)/i);
  const boxMatch = raw.match(/(?:motor)?\s*box\s*(no|number)?\s*[:\-=]\s*([A-Za-z0-9\-_/]+)/i);
  const serial = serialMatch ? serialMatch[2].trim() : '';
  const box = boxMatch ? boxMatch[2].trim() : '';
  if (serial || box) return { serial, box: box || '' };

  return null;
}

function getUpdateInitialData(agreement: RentalAgreement | null): Record<string, unknown> {
  if (!agreement) return {};
  return {
    agreementNo: agreement.agreementNo,
    customerName: agreement.customerName,
    startDate: agreement.startDate,
    endDate: agreement.endDate || '',
    monthlyRent: agreement.monthlyRent,
    status: agreement.status,
  };
}

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

const MachineAssignPage: React.FC = () => {
  const [step, setStep] = useState<1 | 2>(1);
  const [agreementNumberInput, setAgreementNumberInput] = useState('');
  const [lookupError, setLookupError] = useState<string | null>(null);
  const [selectedAgreement, setSelectedAgreement] = useState<RentalAgreement | null>(null);
  const [agreements, setAgreements] = useState<RentalAgreement[]>(mockRentalAgreements);

  const [machinesForAgreement, setMachinesForAgreement] = useState<MachineForAgreement[]>([]);
  const [activeScanCategoryIndex, setActiveScanCategoryIndex] = useState<number | null>(null);
  const [scannerKey, setScannerKey] = useState(1);
  const activeScanCategoryIndexRef = useRef<number | null>(null);
  const [isSubmitting, setIsSubmitting] = useState(false);

  useEffect(() => {
    activeScanCategoryIndexRef.current = activeScanCategoryIndex;
  }, [activeScanCategoryIndex]);

  /** True when all expected categories have reached their required quantity. */
  const isAllCategoriesComplete = (): boolean => {
    if (!selectedAgreement) return false;
    const categories = getExpectedCategories(selectedAgreement);
    return categories.every((cat, i) => {
      const scanned = machinesForAgreement.filter((m) => m.categoryIndex === i).length;
      return scanned >= cat.quantity;
    });
  };

  const checkAndUpdateStatus = (currentMachines: MachineForAgreement[]) => {
    if (!selectedAgreement || selectedAgreement.status !== 'Pending') return;
    const added = currentMachines.length;
    setSelectedAgreement((prev) =>
      prev ? { ...prev, addedMachines: added } : null
    );
  };

  const handleRemoveMachineFromAgreement = (machineId: string) => {
    const updated = machinesForAgreement.filter((m) => m.id !== machineId);
    setMachinesForAgreement(updated);
    checkAndUpdateStatus(updated);
  };

  const handleOpenQRScanner = (categoryIndex: number) => {
    if (!selectedAgreement) return;
    const categories = getExpectedCategories(selectedAgreement);
    if (categoryIndex < 0 || categoryIndex >= categories.length) return;
    const cat = categories[categoryIndex];
    const scannedInCategory = machinesForAgreement.filter((m) => m.categoryIndex === categoryIndex).length;
    if (scannedInCategory >= cat.quantity) {
      alert(`All ${cat.quantity} machine(s) for this category have been added.`);
      return;
    }
    setActiveScanCategoryIndex(categoryIndex);
    setScannerKey((k) => k + 1);
  };

  /** QR code contains only serial number and box number. No brand/model/type. */
  const handleInlineQRScanSuccess = (decodedText: string) => {
    const categoryIndex = activeScanCategoryIndexRef.current;
    if (categoryIndex == null || !selectedAgreement) return;

    const extracted = extractSerialAndBoxFromQR(decodedText);
    if (!extracted || !extracted.serial.trim()) {
      alert('Invalid QR code: Could not read serial number. QR should contain serial number and box number only.');
      setScannerKey((k) => k + 1);
      return;
    }

    const serialNumber = extracted.serial.trim();
    const boxNumber = (extracted.box || '').trim();

    setMachinesForAgreement((prev) => {
      const isDuplicate = prev.some(
        (m) => m.serialNumber.toLowerCase() === serialNumber.toLowerCase()
      );
      if (isDuplicate) {
        setTimeout(() => {
          alert('This machine is already assigned to this agreement.');
          setScannerKey((k) => k + 1);
        }, 0);
        return prev;
      }
      const newMachine: MachineForAgreement = {
        id: Date.now().toString(),
        description: boxNumber ? `Serial: ${serialNumber} · Box: ${boxNumber}` : `Serial: ${serialNumber}`,
        serialNumber,
        boxNumber: boxNumber || '',
        scannedAt: new Date().toISOString(),
        categoryIndex,
      };
      const updated = [...prev, newMachine];
      checkAndUpdateStatus(updated);
      const categories = getExpectedCategories(selectedAgreement);
      const cat = categories[categoryIndex];
      const scannedInCat = updated.filter((m) => m.categoryIndex === categoryIndex).length;
      if (cat && scannedInCat >= cat.quantity) {
        setActiveScanCategoryIndex(null);
      }
      setTimeout(() => setScannerKey((k) => k + 1), 0);
      return updated;
    });
  };

  const handleContinueFromStep1 = () => {
    const trimmed = agreementNumberInput.trim();
    if (!trimmed) {
      setLookupError('Please enter an agreement number.');
      return;
    }
    const found = findAgreementByNumber(trimmed);
    if (!found) {
      setLookupError('Agreement not found. Please check the number.');
      return;
    }
    setLookupError(null);
    setMachinesForAgreement([]);
    setActiveScanCategoryIndex(null);
    setSelectedAgreement(found);
    setStep(2);
  };

  const handleBackToStep1 = () => {
    setStep(1);
    setAgreementNumberInput('');
    setLookupError(null);
    setSelectedAgreement(null);
    setMachinesForAgreement([]);
    setActiveScanCategoryIndex(null);
  };

  const handleCloseUpdate = () => {
    setSelectedAgreement(null);
    setMachinesForAgreement([]);
    setActiveScanCategoryIndex(null);
    setStep(1);
    setAgreementNumberInput('');
  };

  const handleAgreementUpdate = async (data: Record<string, unknown>) => {
    if (!selectedAgreement) return;
    const wasPending = selectedAgreement.status === 'Pending';
    const categories = getExpectedCategories(selectedAgreement);
    const totalExpected = categories.reduce((sum, c) => sum + c.quantity, 0);

    if (wasPending && totalExpected > 0 && !isAllCategoriesComplete()) {
      alert(
        'Please complete machine assignment for all categories before submitting. Scan QR for each category until the required count is reached.'
      );
      return;
    }

    setIsSubmitting(true);
    try {
      const addedCount = machinesForAgreement.length;
      const newStatus =
        wasPending && totalExpected > 0 && addedCount >= totalExpected
          ? 'Active'
          : (data.status as RentalStatus) ?? selectedAgreement.status;

      setAgreements((prev) =>
        prev.map((a) =>
          a.id === selectedAgreement.id
            ? { ...a, ...data, status: newStatus, addedMachines: addedCount }
            : a
        )
      );

      if (newStatus === 'Active' && wasPending && addedCount > 0) {
        const customer = mockCustomers.find((c) => c.id === selectedAgreement.customerNo);
        const monthlyRent = selectedAgreement.monthlyRent;
        const rentPerMachine = addedCount > 0 ? monthlyRent / addedCount : 0;
        const today = new Date().toISOString().split('T')[0];
        const periodFrom = selectedAgreement.startDate;
        const periodTo =
          selectedAgreement.endDate ||
          new Date(new Date(selectedAgreement.startDate).getTime() + 30 * 24 * 60 * 60 * 1000).toISOString().split('T')[0];

        const itemsByCategory = new Map<number, MachineForAgreement[]>();
        machinesForAgreement.forEach((m) => {
          const idx = m.categoryIndex ?? 0;
          if (!itemsByCategory.has(idx)) itemsByCategory.set(idx, []);
          itemsByCategory.get(idx)!.push(m);
        });
        const catList = getExpectedCategories(selectedAgreement);
        const invoiceItems: AutoGeneratedInvoiceItem[] = [];
        catList.forEach((cat, i) => {
          const machinesInCat = itemsByCategory.get(i) || [];
          const count = machinesInCat.length;
          if (count === 0) return;
          const desc = [cat.brand, cat.model, cat.type].filter(Boolean).join(' ') || 'Machine';
          const subtotal = count * rentPerMachine;
          invoiceItems.push({
            id: String(invoiceItems.length + 1),
            itemCode: `212WG${String(invoiceItems.length + 1).padStart(5, '0')}`,
            description: desc.toUpperCase(),
            brand: cat.brand,
            model: cat.model,
            type: cat.type,
            numberOfMachines: count,
            monthlyRentPerMachine: rentPerMachine,
            subtotal,
          });
        });
        const subtotal = invoiceItems.reduce((s, it) => s + it.subtotal, 0);
        const vatAmount = Math.round(subtotal * 0.18);
        const totalAmount = subtotal + vatAmount;
        const generatedInvoice: AutoGeneratedInvoice = {
          invoiceNumber: `RA-${selectedAgreement.agreementNo}-${Date.now().toString().slice(-6)}`,
          customerName: selectedAgreement.customerName,
          customerAddress: customer?.address || '',
          vatTinNic: (customer as { vatTinNic?: string })?.vatTinNic ?? customer?.id ?? '',
          invoiceDate: today,
          periodFrom,
          periodTo,
          items: invoiceItems,
          subtotal,
          vatAmount,
          totalAmount,
          status: 'issued',
        };
        try {
          localStorage.setItem('needletech_autoGeneratedInvoice', JSON.stringify(generatedInvoice));
        } catch {
          // ignore
        }
        alert(
          `Rental Agreement "${data.agreementNo}" is now Active. Invoice has been generated. You can view it from the Invoice page.`
        );
      } else {
        alert(`Rental Agreement "${data.agreementNo}" updated successfully.`);
      }

      handleCloseUpdate();
    } finally {
      setIsSubmitting(false);
    }
  };


  // Render Step 1: Agreement selection
  if (step === 1) {
    return (
      <div className="min-h-screen w-full bg-gradient-to-br from-slate-900 via-slate-800 to-slate-900">
        {/* Header */}
        <div className="bg-slate-900/80 backdrop-blur-sm border-b border-slate-700/50 px-4 py-4">
          <div className="max-w-md mx-auto">
            <h1 className="text-xl font-bold text-white flex items-center gap-2">
              <Scan className="w-6 h-6" />
              Scan Inventory
            </h1>
            <p className="text-sm text-slate-400 mt-1">Enter agreement number to start scanning</p>
          </div>
        </div>

        {/* Content */}
        <div className="px-4 py-8">
          <div className="max-w-md mx-auto space-y-4">
            <div className="bg-slate-800/50 backdrop-blur-sm rounded-2xl border border-slate-700/50 p-6 space-y-4">
              <label htmlFor="agreement-input" className="block text-sm font-medium text-slate-300">
                Agreement Number
              </label>
              <input
                id="agreement-input"
                type="text"
                autoComplete="off"
                value={agreementNumberInput}
                onChange={(e) => {
                  setAgreementNumberInput(e.target.value);
                  setLookupError(null);
                }}
                onKeyDown={(e) => e.key === 'Enter' && handleContinueFromStep1()}
                placeholder="e.g. RA24010006"
                className="w-full min-h-[52px] px-4 py-3 text-base border rounded-xl bg-slate-700/50 text-white border-slate-600 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent placeholder:text-slate-500"
                autoFocus
              />
              {lookupError && (
                <p className="text-sm text-red-400 flex items-center gap-2" role="alert">
                  <span className="w-1.5 h-1.5 bg-red-400 rounded-full"></span>
                  {lookupError}
                </p>
              )}
              <p className="text-xs text-slate-500">
                Try: RA24010002, RA24010005, RA24010006
              </p>
              <button
                type="button"
                onClick={handleContinueFromStep1}
                className="w-full min-h-[52px] px-4 py-3 text-base font-semibold text-white bg-blue-600 rounded-xl hover:bg-blue-700 active:scale-[0.98] transition-all touch-manipulation flex items-center justify-center gap-2"
              >
                <CheckCircle2 className="w-5 h-5" />
                Start Scanning
              </button>
            </div>
          </div>
        </div>
      </div>
    );
  }

  // Render Step 2: Scanning interface
  if (!selectedAgreement) return null;

  const categories = getExpectedCategories(selectedAgreement);
  const totalExpected = categories.reduce((sum, c) => sum + c.quantity, 0);
  const totalScanned = machinesForAgreement.length;
  const allComplete = isAllCategoriesComplete();
  const latestMachine = machinesForAgreement[machinesForAgreement.length - 1];
  const previousMachines = machinesForAgreement.slice(0, -1).reverse();

  const currentCategoryIndex = activeScanCategoryIndex !== null ? activeScanCategoryIndex : 
    categories.findIndex((cat, i) => {
      const scanned = machinesForAgreement.filter((m) => m.categoryIndex === i).length;
      return scanned < cat.quantity;
    });

  const canStartScanning = currentCategoryIndex >= 0 && currentCategoryIndex < categories.length;

  return (
    <div className="min-h-screen w-full bg-gradient-to-br from-slate-900 via-slate-800 to-slate-900 flex flex-col">
      {/* Header */}
      <div className="bg-slate-900/80 backdrop-blur-sm border-b border-slate-700/50 px-4 py-3 flex items-center justify-between">
        <button
          type="button"
          onClick={handleBackToStep1}
          className="p-2 hover:bg-slate-800 rounded-lg transition-colors"
          aria-label="Go back"
        >
          <ArrowLeft className="w-5 h-5 text-white" />
        </button>
        <div className="flex-1 text-center">
          <h1 className="text-lg font-bold text-white">Scan Inventory</h1>
          <p className="text-xs text-slate-400">Batch #{selectedAgreement.agreementNo}</p>
        </div>
        <div className="flex items-center gap-2">
          <Zap className="w-5 h-5 text-yellow-400" />
          <Scan className="w-5 h-5 text-white" />
        </div>
      </div>

      {/* QR Scanner Section */}
      <div className="flex-1 flex flex-col">
        <div className="relative flex-shrink-0 bg-black/60 backdrop-blur-sm" style={{ height: '45vh', minHeight: '280px' }}>
          {activeScanCategoryIndex !== null ? (
            <div className="absolute inset-0">
              <QRScannerComponent
                key={scannerKey}
                onScanSuccess={handleInlineQRScanSuccess}
                autoClose={false}
                showCloseButton={false}
                title=""
                subtitle=""
                embedded
              />
              <div className="absolute top-4 left-1/2 -translate-x-1/2 text-center">
                <p className="text-sm text-slate-300 font-medium">Align QR code within frame</p>
              </div>
              <div className="absolute bottom-4 left-1/2 -translate-x-1/2">
                <p className="text-xs text-slate-400">Auto-detecting...</p>
              </div>
            </div>
          ) : (
            <div className="absolute inset-0 flex items-center justify-center">
              <div className="text-center px-6">
                <div className="w-24 h-24 mx-auto mb-4 rounded-2xl bg-slate-800/50 border-2 border-dashed border-slate-600 flex items-center justify-center">
                  <Scan className="w-12 h-12 text-slate-500" />
                </div>
                <p className="text-slate-300 font-medium mb-2">Ready to scan</p>
                <p className="text-xs text-slate-500">Tap the button below to start scanning</p>
              </div>
            </div>
          )}
        </div>

        {/* Progress Section */}
        <div className="flex-1 bg-slate-800/30 backdrop-blur-sm px-4 py-4 overflow-y-auto">
          <div className="max-w-2xl mx-auto space-y-4">
            {/* Scanning Progress Header */}
            <div className="flex items-center justify-between">
              <div>
                <h2 className="text-lg font-bold text-white">Scanning Progress</h2>
                <p className="text-xs text-slate-400">Job ID: #{selectedAgreement.agreementNo}</p>
              </div>
              <div className="flex items-center gap-3 bg-slate-800/50 rounded-xl px-4 py-2 border border-slate-700/50">
                <div className="text-center">
                  <div className="text-2xl font-bold text-white tabular-nums">
                    {totalScanned}
                  </div>
                  <div className="text-xs text-slate-400">Scanned</div>
                </div>
                <div className="w-px h-8 bg-slate-700"></div>
                <div className="text-center">
                  <div className="text-2xl font-bold text-white tabular-nums">
                    {totalExpected}
                  </div>
                  <div className="text-xs text-slate-400">Total</div>
                </div>
              </div>
            </div>

            {/* Progress Bar */}
            <div className="space-y-2">
              <div className="w-full bg-slate-700/50 rounded-full h-1.5 overflow-hidden">
                <div
                  className={`h-1.5 rounded-full transition-all duration-500 ${
                    allComplete ? 'bg-green-500' : 'bg-blue-500'
                  }`}
                  style={{ width: `${totalExpected > 0 ? (totalScanned / totalExpected) * 100 : 0}%` }}
                />
              </div>
            </div>

            {/* Latest Scan */}
            {latestMachine && (
              <div className="bg-gradient-to-r from-emerald-900/30 to-teal-900/30 backdrop-blur-sm border border-emerald-700/50 rounded-xl p-4">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-3 flex-1 min-w-0">
                    <div className="flex-shrink-0 w-10 h-10 bg-emerald-500 rounded-full flex items-center justify-center">
                      <CheckCircle2 className="w-6 h-6 text-white" />
                    </div>
                    <div className="flex-1 min-w-0">
                      <p className="text-base font-bold text-emerald-300 truncate">
                        {latestMachine.serialNumber}
                      </p>
                      <p className="text-sm text-emerald-400/80">
                        Box {latestMachine.boxNumber || '—'} • Added
                      </p>
                    </div>
                  </div>
                  <button
                    type="button"
                    onClick={() => handleRemoveMachineFromAgreement(latestMachine.id)}
                    className="flex-shrink-0 p-2 hover:bg-slate-800/50 rounded-lg transition-colors"
                    aria-label="Undo last scan"
                  >
                    <RotateCcw className="w-5 h-5 text-slate-400" />
                  </button>
                </div>
              </div>
            )}

            {/* Previous Scans */}
            {previousMachines.length > 0 && (
              <div className="space-y-2">
                <h3 className="text-xs font-semibold text-slate-400 uppercase tracking-wider">
                  Previous Scans
                </h3>
                <div className="space-y-2 max-h-40 overflow-y-auto">
                  {previousMachines.map((machine) => (
                    <div
                      key={machine.id}
                      className="bg-slate-800/30 backdrop-blur-sm border border-slate-700/50 rounded-lg p-3 flex items-center justify-between"
                    >
                      <div className="flex items-center gap-3 flex-1 min-w-0">
                        <div className="flex-shrink-0 w-8 h-8 bg-slate-700/50 rounded-lg flex items-center justify-center">
                          <Scan className="w-4 h-4 text-slate-400" />
                        </div>
                        <div className="flex-1 min-w-0">
                          <p className="text-sm font-semibold text-white truncate">
                            {machine.serialNumber}
                          </p>
                          <p className="text-xs text-slate-400">
                            Box {machine.boxNumber || '—'}
                          </p>
                        </div>
                      </div>
                      <button
                        type="button"
                        onClick={() => handleRemoveMachineFromAgreement(machine.id)}
                        className="flex-shrink-0 p-2 hover:bg-slate-700/50 rounded-lg transition-colors"
                        aria-label="Delete scan"
                      >
                        <Trash2 className="w-4 h-4 text-slate-400" />
                      </button>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Start/Resume Scanning Button */}
            {!allComplete && canStartScanning && activeScanCategoryIndex === null && (
              <button
                type="button"
                onClick={() => handleOpenQRScanner(currentCategoryIndex)}
                className="w-full min-h-[56px] px-6 py-3 text-base font-semibold text-white bg-blue-600 rounded-xl hover:bg-blue-700 active:scale-[0.98] transition-all touch-manipulation flex items-center justify-center gap-2"
              >
                <Scan className="w-5 h-5" />
                {totalScanned === 0 ? 'Start Scanning' : 'Resume Scanning'}
              </button>
            )}

            {/* Done Scanning Button */}
            {(allComplete || totalScanned > 0) && activeScanCategoryIndex === null && (
              <button
                type="button"
                onClick={async () => {
                  if (!allComplete) {
                    const confirm = window.confirm(
                      `You've scanned ${totalScanned} of ${totalExpected} machines. Are you sure you want to finish?`
                    );
                    if (!confirm) return;
                  }
                  
                  setIsSubmitting(true);
                  try {
                    const data = getUpdateInitialData(selectedAgreement);
                    await handleAgreementUpdate({ ...data, status: 'Active' });
                  } finally {
                    setIsSubmitting(false);
                  }
                }}
                disabled={isSubmitting}
                className="w-full min-h-[56px] px-6 py-3 text-base font-semibold text-white bg-blue-600 rounded-xl hover:bg-blue-700 active:scale-[0.98] transition-all touch-manipulation flex items-center justify-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed"
              >
                <CheckCircle2 className="w-5 h-5" />
                {isSubmitting ? 'Processing...' : 'Done Scanning'}
              </button>
            )}

            {totalScanned === 0 && (
              <div className="text-center py-8 px-4">
                <Scan className="w-12 h-12 text-slate-600 mx-auto mb-3" />
                <p className="text-sm font-medium text-slate-400">No machines scanned yet</p>
                <p className="text-xs text-slate-500 mt-1">
                  Scan QR codes to add machines to this batch
                </p>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};

export default MachineAssignPage;
