'use client';

import React, { useState, useRef, useEffect } from 'react';
import Navbar from '@/src/components/common/navbar';
import UpdateForm from '@/src/components/form-popup/update';
import QRScannerComponent from '@/src/components/qr-scanner';
import {
  X,
  QrCode,
  CheckCircle2,
  Trash2,
  FileText,
  Cpu,
  ArrowLeft,
} from 'lucide-react';

// ---------------------------------------------------------------------------
// Types (aligned with rental-agreement page)
// ---------------------------------------------------------------------------

type RentalStatus = 'Active' | 'Completed' | 'Cancelled' | 'Pending';

interface ExpectedMachineCategory {
  id: string;
  brand: string;
  model: string;
  type: string;
  quantity: number;
}

interface RentalAgreement {
  id: number;
  agreementNo: string;
  customerNo: string;
  customerName: string;
  serialNo: string;
  startDate: string;
  endDate: string | null;
  monthlyRent: number;
  outstanding: number;
  status: RentalStatus;
  purchaseRequestId?: number;
  purchaseRequestNumber?: string;
  expectedMachines?: number;
  addedMachines?: number;
  expectedMachineCategories?: ExpectedMachineCategory[];
}

interface MachineForAgreement {
  id: string;
  description: string;
  serialNumber: string;
  boxNumber: string;
  brandName?: string;
  modelName?: string;
  typeName?: string;
  scannedAt?: string;
  categoryIndex?: number;
}

// Minimal invoice shape for auto-generated invoice (from rental-agreement)
interface AutoGeneratedInvoiceItem {
  id: string;
  itemCode: string;
  description: string;
  serialNumber?: string;
  brand: string;
  model: string;
  type: string;
  numberOfMachines: number;
  monthlyRentPerMachine: number;
  subtotal: number;
}
interface AutoGeneratedInvoice {
  invoiceNumber: string;
  customerName: string;
  customerAddress: string;
  vatTinNic: string;
  invoiceDate: string;
  periodFrom: string;
  periodTo: string;
  items: AutoGeneratedInvoiceItem[];
  subtotal: number;
  vatAmount: number;
  totalAmount: number;
  status: 'issued';
}

// ---------------------------------------------------------------------------
// Mock data (same Pending agreements as rental-agreement for consistency)
// ---------------------------------------------------------------------------

const mockCustomers = [
  { id: 'CUST-001', name: 'ABC Holdings (Pvt) Ltd', address: '123 Main Street, Colombo 05' },
  { id: 'CUST-002', name: 'John Perera', address: '456 Galle Road, Mount Lavinia' },
  { id: 'CUST-005', name: 'Mega Constructions', address: '654 High Level Road, Maharagama' },
  { id: 'CUST-006', name: 'VIHANGA SHADE STRUCTURES', address: '317/2, NEW KANDY ROAD, BIYAGAMA' },
];

const mockRentalAgreements: RentalAgreement[] = [
  {
    id: 2,
    agreementNo: 'RA24010002',
    customerNo: 'CUST-002',
    customerName: 'John Perera',
    serialNo: 'SN-2024-004',
    startDate: '2024-03-01',
    endDate: '2024-06-01',
    monthlyRent: 35000,
    outstanding: 70000,
    status: 'Pending',
    expectedMachines: 1,
    addedMachines: 0,
  },
  {
    id: 5,
    agreementNo: 'RA24010005',
    customerNo: 'CUST-005',
    customerName: 'Mega Constructions',
    serialNo: 'SN-2024-005',
    startDate: '2024-04-01',
    endDate: '2024-07-01',
    monthlyRent: 60000,
    outstanding: 180000,
    status: 'Pending',
    purchaseRequestId: 3,
    purchaseRequestNumber: 'PO24010003',
    expectedMachines: 15,
    addedMachines: 0,
    expectedMachineCategories: [
      { id: 'cat-5-1', brand: 'Juki', model: 'Model A', type: 'Industrial', quantity: 10 },
      { id: 'cat-5-2', brand: 'Juki', model: 'Model B', type: 'Industrial', quantity: 5 },
    ],
  },
  {
    id: 6,
    agreementNo: 'RA24010006',
    customerNo: 'CUST-006',
    customerName: 'VIHANGA SHADE STRUCTURES',
    serialNo: '2LIDH01733',
    startDate: '2026-01-02',
    endDate: '2026-08-01',
    monthlyRent: 17000,
    outstanding: 0,
    status: 'Pending',
    expectedMachines: 1,
    expectedMachineCategories: [
      { id: 'cat-6-1', brand: 'Juki', model: 'LK-1903A-SS', type: 'Electronic Bar Tack Machine', quantity: 1 },
    ],
  },
];

/** Get expected machine categories for an agreement. */
function getExpectedCategories(agreement: RentalAgreement | null): ExpectedMachineCategory[] {
  if (!agreement) return [];
  const cats = agreement.expectedMachineCategories;
  if (cats && cats.length > 0) return cats;
  const total = agreement.expectedMachines ?? 0;
  if (total <= 0) return [];
  return [{ id: 'default', brand: '', model: 'Machine', type: '', quantity: total }];
}

function findAgreementByNumber(agreementNo: string): RentalAgreement | undefined {
  const normalized = (agreementNo || '').trim().toUpperCase();
  if (!normalized) return undefined;
  return mockRentalAgreements.find(
    (a) =>
      a.agreementNo.toUpperCase() === normalized ||
      a.agreementNo.replace(/\s/g, '') === normalized.replace(/\s/g, '')
  );
}

/** QR contains only serial number and box number. Extract from JSON or key: value text. */
function extractSerialAndBoxFromQR(decodedText: string): { serial: string; box: string } | null {
  const raw = (decodedText || '').trim();
  if (!raw) return null;

  try {
    const parsed = JSON.parse(raw);
    if (parsed && typeof parsed === 'object') {
      const serialCandidates = [
        parsed.serialNo,
        parsed.serialNO,
        parsed.serial,
        parsed.serialNumber,
        parsed.SerialNo,
        parsed.Serial,
        parsed.machineSerial,
        parsed.machineSerialNo,
      ].filter((v: unknown) => typeof v === 'string' && (v as string).trim().length > 0);
      const boxCandidates = [
        parsed.motorBoxNo,
        parsed.boxNo,
        parsed.boxNumber,
        parsed.MotorBoxNo,
        parsed.BoxNo,
        parsed.box,
      ].filter((v: unknown) => typeof v === 'string' && (v as string).trim().length > 0);
      const serial = serialCandidates.length > 0 ? (serialCandidates[0] as string).trim() : '';
      const box = boxCandidates.length > 0 ? (boxCandidates[0] as string).trim() : '';
      if (serial || box) return { serial, box: box || '' };
    }
  } catch {
    // not JSON, try key: value pattern
  }

  const serialMatch = raw.match(/serial\s*(no|number)?\s*[:\-=]\s*([A-Za-z0-9\-_/]+)/i);
  const boxMatch = raw.match(/(?:motor)?\s*box\s*(no|number)?\s*[:\-=]\s*([A-Za-z0-9\-_/]+)/i);
  const serial = serialMatch ? serialMatch[2].trim() : '';
  const box = boxMatch ? boxMatch[2].trim() : '';
  if (serial || box) return { serial, box: box || '' };

  return null;
}

// ---------------------------------------------------------------------------
// Update form fields (same as rental-agreement)
// ---------------------------------------------------------------------------

const updateFields = [
  { name: 'agreementNo', label: 'Agreement Number', type: 'text' as const, placeholder: 'Enter agreement number', required: true, disabled: true },
  { name: 'customerName', label: 'Customer Name', type: 'text' as const, placeholder: 'Enter customer name', required: true, disabled: true },
  { name: 'startDate', label: 'Start Date', type: 'date' as const, placeholder: 'Select start date', required: true },
  { name: 'endDate', label: 'End Date', type: 'date' as const, placeholder: 'Select end date', required: false },
  { name: 'monthlyRent', label: 'Monthly Rent', type: 'number' as const, placeholder: 'Enter monthly rent', required: true },
  {
    name: 'status',
    label: 'Status',
    type: 'select' as const,
    placeholder: 'Select status',
    required: true,
    options: [
      { label: 'Active', value: 'Active' },
      { label: 'Completed', value: 'Completed' },
      { label: 'Cancelled', value: 'Cancelled' },
      { label: 'Pending', value: 'Pending' },
    ],
  },
];

function getUpdateInitialData(agreement: RentalAgreement | null): Record<string, unknown> {
  if (!agreement) return {};
  return {
    agreementNo: agreement.agreementNo,
    customerName: agreement.customerName,
    startDate: agreement.startDate,
    endDate: agreement.endDate || '',
    monthlyRent: agreement.monthlyRent,
    status: agreement.status,
  };
}

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

const MachineAssignPage: React.FC = () => {
  const [step, setStep] = useState<1 | 2>(1);
  const [agreementNumberInput, setAgreementNumberInput] = useState('');
  const [lookupError, setLookupError] = useState<string | null>(null);
  const [selectedAgreement, setSelectedAgreement] = useState<RentalAgreement | null>(null);
  const [agreements, setAgreements] = useState<RentalAgreement[]>(mockRentalAgreements);

  const [machinesForAgreement, setMachinesForAgreement] = useState<MachineForAgreement[]>([]);
  const [activeScanCategoryIndex, setActiveScanCategoryIndex] = useState<number | null>(null);
  const [scannerKey, setScannerKey] = useState(1);
  const activeScanCategoryIndexRef = useRef<number | null>(null);
  const [isSubmitting, setIsSubmitting] = useState(false);

  useEffect(() => {
    activeScanCategoryIndexRef.current = activeScanCategoryIndex;
  }, [activeScanCategoryIndex]);

  /** True when all expected categories have reached their required quantity. */
  const isAllCategoriesComplete = (): boolean => {
    if (!selectedAgreement) return false;
    const categories = getExpectedCategories(selectedAgreement);
    return categories.every((cat, i) => {
      const scanned = machinesForAgreement.filter((m) => m.categoryIndex === i).length;
      return scanned >= cat.quantity;
    });
  };

  const checkAndUpdateStatus = (currentMachines: MachineForAgreement[]) => {
    if (!selectedAgreement || selectedAgreement.status !== 'Pending') return;
    const added = currentMachines.length;
    setSelectedAgreement((prev) =>
      prev ? { ...prev, addedMachines: added } : null
    );
  };

  const handleRemoveMachineFromAgreement = (machineId: string) => {
    const updated = machinesForAgreement.filter((m) => m.id !== machineId);
    setMachinesForAgreement(updated);
    checkAndUpdateStatus(updated);
  };

  const handleOpenQRScanner = (categoryIndex: number) => {
    if (!selectedAgreement) return;
    const categories = getExpectedCategories(selectedAgreement);
    if (categoryIndex < 0 || categoryIndex >= categories.length) return;
    const cat = categories[categoryIndex];
    const scannedInCategory = machinesForAgreement.filter((m) => m.categoryIndex === categoryIndex).length;
    if (scannedInCategory >= cat.quantity) {
      alert(`All ${cat.quantity} machine(s) for this category have been added.`);
      return;
    }
    setActiveScanCategoryIndex(categoryIndex);
    setScannerKey((k) => k + 1);
  };

  /** QR code contains only serial number and box number. No brand/model/type. */
  const handleInlineQRScanSuccess = (decodedText: string) => {
    const categoryIndex = activeScanCategoryIndexRef.current;
    if (categoryIndex == null || !selectedAgreement) return;

    const extracted = extractSerialAndBoxFromQR(decodedText);
    if (!extracted || !extracted.serial.trim()) {
      alert('Invalid QR code: Could not read serial number. QR should contain serial number and box number only.');
      setScannerKey((k) => k + 1);
      return;
    }

    const serialNumber = extracted.serial.trim();
    const boxNumber = (extracted.box || '').trim();

    setMachinesForAgreement((prev) => {
      const isDuplicate = prev.some(
        (m) => m.serialNumber.toLowerCase() === serialNumber.toLowerCase()
      );
      if (isDuplicate) {
        setTimeout(() => {
          alert('This machine is already assigned to this agreement.');
          setScannerKey((k) => k + 1);
        }, 0);
        return prev;
      }
      const newMachine: MachineForAgreement = {
        id: Date.now().toString(),
        description: boxNumber ? `Serial: ${serialNumber} · Box: ${boxNumber}` : `Serial: ${serialNumber}`,
        serialNumber,
        boxNumber: boxNumber || '',
        scannedAt: new Date().toISOString(),
        categoryIndex,
      };
      const updated = [...prev, newMachine];
      checkAndUpdateStatus(updated);
      const categories = getExpectedCategories(selectedAgreement);
      const cat = categories[categoryIndex];
      const scannedInCat = updated.filter((m) => m.categoryIndex === categoryIndex).length;
      if (cat && scannedInCat >= cat.quantity) {
        setActiveScanCategoryIndex(null);
      }
      setTimeout(() => setScannerKey((k) => k + 1), 0);
      return updated;
    });
  };

  const handleContinueFromStep1 = () => {
    const trimmed = agreementNumberInput.trim();
    if (!trimmed) {
      setLookupError('Please enter an agreement number.');
      return;
    }
    const found = findAgreementByNumber(trimmed);
    if (!found) {
      setLookupError('Agreement not found. Please check the number.');
      return;
    }
    setLookupError(null);
    setMachinesForAgreement([]);
    setActiveScanCategoryIndex(null);
    setSelectedAgreement(found);
    setStep(2);
  };

  const handleBackToStep1 = () => {
    setStep(1);
    setAgreementNumberInput('');
    setLookupError(null);
    setSelectedAgreement(null);
    setMachinesForAgreement([]);
    setActiveScanCategoryIndex(null);
  };

  const handleCloseUpdate = () => {
    setSelectedAgreement(null);
    setMachinesForAgreement([]);
    setActiveScanCategoryIndex(null);
    setStep(1);
    setAgreementNumberInput('');
  };

  const handleAgreementUpdate = async (data: Record<string, unknown>) => {
    if (!selectedAgreement) return;
    const wasPending = selectedAgreement.status === 'Pending';
    const categories = getExpectedCategories(selectedAgreement);
    const totalExpected = categories.reduce((sum, c) => sum + c.quantity, 0);

    if (wasPending && totalExpected > 0 && !isAllCategoriesComplete()) {
      alert(
        'Please complete machine assignment for all categories before submitting. Scan QR for each category until the required count is reached.'
      );
      return;
    }

    setIsSubmitting(true);
    try {
      const addedCount = machinesForAgreement.length;
      const newStatus =
        wasPending && totalExpected > 0 && addedCount >= totalExpected
          ? 'Active'
          : (data.status as RentalStatus) ?? selectedAgreement.status;

      setAgreements((prev) =>
        prev.map((a) =>
          a.id === selectedAgreement.id
            ? { ...a, ...data, status: newStatus, addedMachines: addedCount }
            : a
        )
      );

      if (newStatus === 'Active' && wasPending && addedCount > 0) {
        const customer = mockCustomers.find((c) => c.id === selectedAgreement.customerNo);
        const monthlyRent = selectedAgreement.monthlyRent;
        const rentPerMachine = addedCount > 0 ? monthlyRent / addedCount : 0;
        const today = new Date().toISOString().split('T')[0];
        const periodFrom = selectedAgreement.startDate;
        const periodTo =
          selectedAgreement.endDate ||
          new Date(new Date(selectedAgreement.startDate).getTime() + 30 * 24 * 60 * 60 * 1000).toISOString().split('T')[0];

        const itemsByCategory = new Map<number, MachineForAgreement[]>();
        machinesForAgreement.forEach((m) => {
          const idx = m.categoryIndex ?? 0;
          if (!itemsByCategory.has(idx)) itemsByCategory.set(idx, []);
          itemsByCategory.get(idx)!.push(m);
        });
        const catList = getExpectedCategories(selectedAgreement);
        const invoiceItems: AutoGeneratedInvoiceItem[] = [];
        catList.forEach((cat, i) => {
          const machinesInCat = itemsByCategory.get(i) || [];
          const count = machinesInCat.length;
          if (count === 0) return;
          const desc = [cat.brand, cat.model, cat.type].filter(Boolean).join(' ') || 'Machine';
          const subtotal = count * rentPerMachine;
          invoiceItems.push({
            id: String(invoiceItems.length + 1),
            itemCode: `212WG${String(invoiceItems.length + 1).padStart(5, '0')}`,
            description: desc.toUpperCase(),
            brand: cat.brand,
            model: cat.model,
            type: cat.type,
            numberOfMachines: count,
            monthlyRentPerMachine: rentPerMachine,
            subtotal,
          });
        });
        const subtotal = invoiceItems.reduce((s, it) => s + it.subtotal, 0);
        const vatAmount = Math.round(subtotal * 0.18);
        const totalAmount = subtotal + vatAmount;
        const generatedInvoice: AutoGeneratedInvoice = {
          invoiceNumber: `RA-${selectedAgreement.agreementNo}-${Date.now().toString().slice(-6)}`,
          customerName: selectedAgreement.customerName,
          customerAddress: customer?.address || '',
          vatTinNic: (customer as { vatTinNic?: string })?.vatTinNic ?? customer?.id ?? '',
          invoiceDate: today,
          periodFrom,
          periodTo,
          items: invoiceItems,
          subtotal,
          vatAmount,
          totalAmount,
          status: 'issued',
        };
        try {
          localStorage.setItem('needletech_autoGeneratedInvoice', JSON.stringify(generatedInvoice));
        } catch {
          // ignore
        }
        alert(
          `Rental Agreement "${data.agreementNo}" is now Active. Invoice has been generated. You can view it from the Invoice page.`
        );
      } else {
        alert(`Rental Agreement "${data.agreementNo}" updated successfully.`);
      }

      handleCloseUpdate();
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleClear = () => {
    // Reset form to initial; optional
  };

  // Machine Assignment section: only for Pending agreements (same as rental-agreement)
  const renderMachineManagementSection = () => {
    if (!selectedAgreement || selectedAgreement.status !== 'Pending') return null;

    const categories = getExpectedCategories(selectedAgreement);
    const totalExpected = categories.reduce((sum, c) => sum + c.quantity, 0);
    const totalScanned = machinesForAgreement.length;
    const allComplete = isAllCategoriesComplete();
    const progressPercentage = totalExpected > 0 ? Math.min((totalScanned / totalExpected) * 100, 100) : 0;

    const getScannedForCategory = (categoryIndex: number) =>
      machinesForAgreement.filter((m) => m.categoryIndex === categoryIndex).length;
    const canScanCategory = (categoryIndex: number) => {
      for (let j = 0; j < categoryIndex; j++) {
        if (getScannedForCategory(j) < categories[j].quantity) return false;
      }
      return getScannedForCategory(categoryIndex) < categories[categoryIndex].quantity;
    };

    return (
      <div className="space-y-4 sm:space-y-6">
        <div className="border-t border-gray-200 dark:border-slate-700 pt-4 sm:pt-6">
          <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 mb-4 sm:mb-5">
            <div className="flex-1 min-w-0">
              <h3 className="text-base sm:text-lg font-semibold text-gray-900 dark:text-white mb-1">Machine Assignment</h3>
              <p className="text-xs sm:text-sm text-gray-600 dark:text-gray-400 break-words">
                Add machines by scanning QR codes for each category. Complete each category in order. QR must contain serial number and box number only.
              </p>
            </div>
            {totalExpected > 0 && (
              <div className="flex items-center gap-3 sm:gap-4 bg-gray-50 dark:bg-slate-700/50 rounded-xl px-4 py-3 sm:px-5 border border-gray-100 dark:border-slate-600/50 w-full sm:w-auto shrink-0">
                <div className="text-center flex-1 sm:flex-initial">
                  <div className="text-xl sm:text-2xl font-bold text-gray-900 dark:text-white tabular-nums">
                    {totalScanned}/{totalExpected}
                  </div>
                  <div className="text-xs text-gray-600 dark:text-gray-400 font-medium">Machines</div>
                </div>
                {allComplete && (
                  <div className="flex items-center text-green-600 dark:text-green-400">
                    <CheckCircle2 className="w-5 h-5 mr-1.5 shrink-0" />
                    <span className="text-xs sm:text-sm font-medium">Complete</span>
                  </div>
                )}
              </div>
            )}
          </div>

          {totalExpected > 0 && (
            <div className="mb-4 sm:mb-5 min-w-0">
              <div className="flex items-center justify-between mb-2 gap-2">
                <span className="text-xs sm:text-sm font-medium text-gray-700 dark:text-gray-300">Progress</span>
                <span className="text-xs sm:text-sm font-semibold text-gray-900 dark:text-white tabular-nums shrink-0">
                  {Math.round(progressPercentage)}%
                </span>
              </div>
              <div className="w-full min-w-0 bg-gray-200 dark:bg-slate-700 rounded-full h-2.5 overflow-hidden">
                <div
                  className={`h-2.5 rounded-full transition-all duration-500 ease-out ${
                    allComplete
                      ? 'bg-gradient-to-r from-green-500 to-emerald-600 dark:from-green-500 dark:to-emerald-600'
                      : 'bg-gradient-to-r from-blue-500 to-indigo-600 dark:from-blue-500 dark:to-indigo-600'
                  }`}
                  style={{ width: `${progressPercentage}%` }}
                />
              </div>
              {allComplete && (
                <p className="mt-2 text-xs sm:text-sm text-green-600 dark:text-green-400 flex items-center gap-1.5 break-words">
                  <CheckCircle2 className="w-4 h-4 shrink-0" />
                  All machines assigned. Submit to activate agreement and generate invoice.
                </p>
              )}
            </div>
          )}

          <div className="space-y-3 sm:space-y-4 mb-4 sm:mb-6">
            {categories.map((cat, i) => {
              const scanned = getScannedForCategory(i);
              const required = cat.quantity;
              const categoryComplete = scanned >= required;
              const canScan = canScanCategory(i);
              const label = [cat.brand, cat.model, cat.type].filter(Boolean).join(' ') || 'Machine';
              return (
                <div
                  key={cat.id}
                  className={`rounded-xl border p-3 sm:p-4 min-w-0 ${
                    categoryComplete
                      ? 'bg-green-50/50 dark:bg-green-900/10 border-green-200 dark:border-green-800/50'
                      : 'bg-gray-50 dark:bg-slate-700/50 border-gray-200 dark:border-slate-600'
                  }`}
                >
                  <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between sm:gap-4">
                    <div className="min-w-0 flex-1">
                      <div className="font-medium text-sm sm:text-base text-gray-900 dark:text-white break-words">
                        {cat.brand && <span>{cat.brand} </span>}
                        {cat.model && <span>{cat.model} </span>}
                        {cat.type && <span>({cat.type})</span>}
                        {!cat.brand && !cat.model && !cat.type && 'Machine'}
                      </div>
                      <p className="text-xs sm:text-sm text-gray-600 dark:text-gray-400 mt-0.5">
                        Enter {required} machine(s) — {scanned} of {required} scanned
                      </p>
                    </div>
                    <button
                      type="button"
                      onClick={() => handleOpenQRScanner(i)}
                      disabled={!canScan}
                      className="w-full sm:w-auto min-h-[44px] flex-shrink-0 px-4 py-2.5 rounded-xl sm:rounded-lg bg-green-600 dark:bg-green-700 text-white text-sm font-medium hover:bg-green-700 dark:hover:bg-green-600 disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2 touch-manipulation active:scale-[0.98]"
                    >
                      <QrCode className="w-4 h-4 shrink-0" />
                      <span className="truncate">{categoryComplete ? 'Complete' : `Scan QR for ${label}`}</span>
                    </button>
                  </div>
                </div>
              );
            })}
          </div>

          {machinesForAgreement.length > 0 && (
            <div className="space-y-3">
              <div className="flex items-center justify-between gap-2 min-w-0">
                <h4 className="text-xs sm:text-sm font-semibold text-gray-700 dark:text-gray-300 truncate">
                  Assigned machines ({machinesForAgreement.length})
                </h4>
                <button
                  type="button"
                  onClick={() => {
                    if (confirm('Remove all machines from this agreement?')) {
                      setMachinesForAgreement([]);
                      checkAndUpdateStatus([]);
                    }
                  }}
                  className="text-xs font-medium text-red-600 dark:text-red-400 hover:underline min-h-[44px] min-w-[44px] flex items-center justify-center touch-manipulation shrink-0"
                  aria-label="Clear all machines"
                >
                  Clear all
                </button>
              </div>
              <div className="space-y-2 max-h-[min(16rem,45vh)] sm:max-h-64 overflow-y-auto overflow-x-hidden pr-1 -mr-1 overscroll-contain">
                {machinesForAgreement.map((machine, index) => (
                  <div
                    key={machine.id}
                    className="bg-white dark:bg-slate-700/80 border border-gray-200 dark:border-slate-600 rounded-xl p-3 sm:p-4 min-w-0"
                  >
                    <div className="flex items-start justify-between gap-2 sm:gap-3">
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center gap-2 mb-1.5 sm:mb-2">
                          <span className="flex-shrink-0 w-6 h-6 sm:w-7 sm:h-7 bg-green-100 dark:bg-green-900/30 text-green-700 dark:text-green-300 rounded-lg flex items-center justify-center text-xs font-semibold">
                            {index + 1}
                          </span>
                          <p className="text-xs sm:text-sm font-medium text-gray-900 dark:text-white truncate min-w-0">
                            {machine.description || 'Machine'}
                          </p>
                        </div>
                        <div className="grid grid-cols-1 sm:grid-cols-2 gap-1 sm:gap-1.5 text-xs text-gray-600 dark:text-gray-400 ml-8 sm:ml-9 break-words">
                          <div className="min-w-0">
                            <span className="font-medium text-gray-500 dark:text-gray-500">Serial:</span>{' '}
                            <span className="break-all">{machine.serialNumber}</span>
                          </div>
                          <div className="min-w-0">
                            <span className="font-medium text-gray-500 dark:text-gray-500">Box:</span> {machine.boxNumber || '—'}
                          </div>
                          {machine.scannedAt && (
                            <div className="sm:col-span-2 text-gray-500 dark:text-gray-500">
                              Scanned{' '}
                              {new Date(machine.scannedAt).toLocaleString('en-LK', { dateStyle: 'short', timeStyle: 'short' })}
                            </div>
                          )}
                        </div>
                      </div>
                      <button
                        type="button"
                        onClick={() => handleRemoveMachineFromAgreement(machine.id)}
                        className="flex-shrink-0 min-h-[44px] min-w-[44px] p-2 flex items-center justify-center text-red-600 dark:text-red-400 hover:bg-red-50 dark:hover:bg-red-900/20 rounded-lg touch-manipulation"
                        title="Remove machine"
                        aria-label="Remove machine"
                      >
                        <Trash2 className="w-4 h-4" />
                      </button>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {machinesForAgreement.length === 0 && (
            <div className="text-center py-8 sm:py-10 px-4 sm:px-6 bg-gray-50 dark:bg-slate-700/30 rounded-xl border-2 border-dashed border-gray-200 dark:border-slate-600">
              <QrCode className="w-10 h-10 sm:w-12 sm:h-12 text-gray-400 dark:text-gray-500 mx-auto mb-2 sm:mb-3" />
              <p className="text-xs sm:text-sm font-medium text-gray-600 dark:text-gray-400">No machines assigned yet</p>
              <p className="text-xs text-gray-500 dark:text-gray-500 mt-1 px-2">
                Use the &quot;Scan QR&quot; button for each category above to add machines. QR must contain serial number and box number only.
              </p>
            </div>
          )}
        </div>
      </div>
    );
  };

  return (
    <div
      className="min-h-screen w-full bg-gray-100 dark:bg-slate-950 overflow-x-hidden"
      style={{
        paddingTop: 'env(safe-area-inset-top)',
        paddingBottom: 'env(safe-area-inset-bottom)',
        paddingLeft: 'env(safe-area-inset-left)',
        paddingRight: 'env(safe-area-inset-right)',
      }}
    >
      <Navbar />

      <main
        className="w-full min-h-0"
        style={{
          paddingTop: 'calc(5rem + env(safe-area-inset-top))',
          paddingBottom: 'calc(1.5rem + env(safe-area-inset-bottom))',
          paddingLeft: 'max(0.75rem, env(safe-area-inset-left))',
          paddingRight: 'max(0.75rem, env(safe-area-inset-right))',
        }}
      >
        <div className="mx-auto max-w-4xl w-full">
          <div className="space-y-4 sm:space-y-5">
            {/* Page title - responsive typography */}
            <div className="min-w-0">
              <h1 className="text-base sm:text-xl md:text-2xl font-semibold text-gray-900 dark:text-white flex items-center gap-2 flex-wrap break-words">
                
                Machine Assignment
              </h1>
              <p className="mt-1 text-xs sm:text-sm text-gray-600 dark:text-gray-400 break-words">
                {step === 1
                  ? 'Enter a rental agreement number to open the update form and assign machines (scan QR when status is Pending).'
                  : 'Update agreement details and assign machines by scanning QR codes for each category.'}
              </p>
            </div>

            {step === 1 ? (
              /* Step 1: Agreement lookup - full width on mobile, max-w on larger */
              <div className="w-full max-w-md">
                <div className="bg-white dark:bg-slate-800 rounded-xl sm:rounded-2xl border border-gray-200 dark:border-slate-700 p-4 sm:p-6 shadow-sm space-y-4">
                  <label htmlFor="agreement-input" className="block text-sm font-medium text-gray-700 dark:text-gray-300">
                    Agreement number
                  </label>
                  <input
                    id="agreement-input"
                    type="text"
                    autoComplete="off"
                    value={agreementNumberInput}
                    onChange={(e) => {
                      setAgreementNumberInput(e.target.value);
                      setLookupError(null);
                    }}
                    onKeyDown={(e) => e.key === 'Enter' && handleContinueFromStep1()}
                    placeholder="e.g. RA24010006"
                    className="w-full min-h-[48px] sm:min-h-[52px] px-4 py-3 text-base border rounded-xl bg-white dark:bg-slate-700 text-gray-900 dark:text-white border-gray-300 dark:border-slate-600 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent dark:focus:ring-indigo-500 touch-manipulation"
                    autoFocus
                  />
                  {lookupError && (
                    <p className="text-sm text-red-600 dark:text-red-400" role="alert">
                      {lookupError}
                    </p>
                  )}
                  <p className="text-xs text-gray-500 dark:text-gray-400 break-words">
                    Pending agreements you can try: RA24010002, RA24010005, RA24010006
                  </p>
                  <button
                    type="button"
                    onClick={handleContinueFromStep1}
                    className="w-full min-h-[48px] sm:min-h-[52px] px-4 py-3 text-base font-medium text-white bg-blue-600 dark:bg-indigo-600 rounded-xl hover:bg-blue-700 dark:hover:bg-indigo-700 active:scale-[0.98] transition-transform touch-manipulation"
                  >
                    Continue
                  </button>
                </div>
              </div>
            ) : selectedAgreement ? (
              <div className="flex flex-col w-full gap-4 min-w-0">
                {/* Top bar: agreement ref + change button - stacks on mobile */}
                <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3 min-w-0">
                  <span className="text-sm font-medium text-gray-700 dark:text-gray-300 truncate flex items-center gap-2 min-w-0">
                    <FileText className="w-4 h-4 text-blue-600 dark:text-blue-400 shrink-0" />
                    <span className="truncate">Agreement: {selectedAgreement.agreementNo}</span>
                  </span>
                  <button
                    type="button"
                    onClick={handleBackToStep1}
                    className="w-full sm:w-auto min-h-[44px] px-4 py-2.5 bg-gray-100 dark:bg-slate-800 text-sm text-gray-700 dark:text-gray-300 font-medium rounded-xl hover:bg-gray-200 dark:hover:bg-slate-700 active:scale-[0.98] touch-manipulation flex items-center justify-center gap-2 shrink-0"
                  >
                    <ArrowLeft className="w-4 h-4 shrink-0" />
                    Change agreement
                  </button>
                </div>

                {/* Update form card - responsive padding and overflow */}
                <div className="bg-white dark:bg-slate-800 rounded-xl sm:rounded-2xl shadow-sm w-full border border-gray-200/50 dark:border-slate-700/50 overflow-hidden min-w-0">
                  <div className="px-4 py-4 sm:px-6 sm:py-5 border-b border-gray-200 dark:border-slate-700 bg-gray-50/50 dark:bg-slate-800/80">
                    <h2 className="text-lg sm:text-xl font-semibold text-gray-900 dark:text-white truncate">
                      Update Rental Agreement
                    </h2>
                  </div>
                  <div className="flex-1 overflow-x-hidden overflow-y-auto p-4 sm:p-6 min-h-0">
                    <UpdateForm
                      title="Update Rental Agreement Details"
                      fields={updateFields}
                      onSubmit={handleAgreementUpdate}
                      onClear={handleClear}
                      submitButtonLabel="Update Agreement"
                      clearButtonLabel="Reset"
                      loading={isSubmitting}
                      initialData={getUpdateInitialData(selectedAgreement)}
                      className="shadow-none border-0 p-0"
                      customSections={renderMachineManagementSection()}
                    />
                  </div>
                </div>
              </div>
            ) : null}
          </div>
        </div>
      </main>

      {/* QR Scanner popup - full-screen on mobile, centered modal on larger */}
      {selectedAgreement && activeScanCategoryIndex !== null && (() => {
        const categories = getExpectedCategories(selectedAgreement);
        const cat = categories[activeScanCategoryIndex];
        const scanned = machinesForAgreement.filter((m) => m.categoryIndex === activeScanCategoryIndex).length;
        const required = cat?.quantity ?? 0;
        const categoryLabel = cat ? [cat.brand, cat.model, cat.type].filter(Boolean).join(' ') || 'Machine' : 'Machine';
        return (
          <div
            className="fixed inset-0 z-[60] flex items-end sm:items-center justify-center p-0 sm:p-4 bg-black/60 backdrop-blur-sm"
            style={{
              paddingLeft: 'env(safe-area-inset-left)',
              paddingRight: 'env(safe-area-inset-right)',
              paddingBottom: 'env(safe-area-inset-bottom)',
            }}
          >
            <div className="flex flex-col w-full h-[95dvh] sm:h-auto sm:max-h-[90vh] sm:max-w-lg bg-white dark:bg-slate-800 rounded-t-2xl sm:rounded-2xl shadow-2xl border border-gray-200 dark:border-slate-700 overflow-hidden">
              <div className="flex-shrink-0 flex items-center justify-between gap-3 px-4 py-3 sm:px-5 sm:py-4 border-b border-gray-200 dark:border-slate-700 bg-gray-50 dark:bg-slate-800/80 min-h-[3.5rem]">
                <div className="min-w-0 flex-1">
                  <h3 className="text-sm sm:text-lg font-semibold text-gray-900 dark:text-white truncate">
                    Scan — {categoryLabel}
                  </h3>
                  <p className="text-xs sm:text-sm text-gray-600 dark:text-gray-400 mt-0.5">
                    {scanned} of {required} scanned · QR: serial & box number only
                  </p>
                </div>
                <button
                  type="button"
                  onClick={() => setActiveScanCategoryIndex(null)}
                  className="flex-shrink-0 min-h-[44px] min-w-[44px] p-2 flex items-center justify-center rounded-xl hover:bg-gray-200 dark:hover:bg-slate-700 text-gray-500 dark:text-gray-400 transition-colors touch-manipulation"
                  aria-label="Close scanner"
                >
                  <X className="w-5 h-5" />
                </button>
              </div>
              <div className="flex-1 min-h-0 flex flex-col w-full min-w-0">
                <div className="flex-1 min-h-[180px] sm:min-h-[240px] min-w-0 w-full overflow-hidden bg-gray-900 dark:bg-black rounded-b-xl sm:rounded-none flex flex-col">
                  <QRScannerComponent
                    key={scannerKey}
                    onScanSuccess={handleInlineQRScanSuccess}
                    autoClose={false}
                    showCloseButton={false}
                    title="Scan machine QR"
                    subtitle={`${scanned}/${required} for this category`}
                    embedded
                  />
                </div>
              </div>
              <div
                className="flex-shrink-0 flex flex-col-reverse sm:flex-row gap-2 sm:gap-3 p-4 sm:px-5 sm:py-4 border-t border-gray-200 dark:border-slate-700 bg-gray-50/50 dark:bg-slate-800/50"
                style={{ paddingBottom: 'max(1rem, env(safe-area-inset-bottom))' }}
              >
                <button
                  type="button"
                  onClick={() => setActiveScanCategoryIndex(null)}
                  className="w-full sm:w-auto min-h-[48px] order-1 sm:order-2 px-4 py-3 sm:py-2.5 text-sm font-medium text-gray-700 dark:text-gray-300 bg-white dark:bg-slate-700 border border-gray-300 dark:border-slate-600 rounded-xl hover:bg-gray-50 dark:hover:bg-slate-600 transition-colors touch-manipulation active:scale-[0.98]"
                >
                  Back to categories
                </button>
                <button
                  type="button"
                  onClick={() => setActiveScanCategoryIndex(null)}
                  className="w-full sm:flex-1 min-h-[48px] order-2 sm:order-1 px-4 py-3 sm:py-2.5 text-sm font-semibold text-white bg-green-600 dark:bg-green-700 rounded-xl hover:bg-green-700 dark:hover:bg-green-600 transition-colors flex items-center justify-center gap-2 touch-manipulation active:scale-[0.98]"
                >
                  <CheckCircle2 className="w-4 h-4 shrink-0" />
                  Complete
                </button>
              </div>
            </div>
          </div>
        );
      })()}
    </div>
  );
};

export default MachineAssignPage;
