'use client';

import React, { useState, useRef, useEffect } from 'react';
import QRScannerComponent from '@/src/components/qr-scanner';
import { authFetch } from '@/lib/auth-client';
import {
  ArrowLeft,
  CheckCircle2,
  RotateCcw,
  Trash2,
  Zap,
  Scan,
  Info,
  Sun,
  Moon,
  Loader2,
} from 'lucide-react';

// ---------------------------------------------------------------------------
// Types (aligned with rental-agreement page)
// ---------------------------------------------------------------------------

type RentalStatus = 'Active' | 'Completed' | 'Cancelled' | 'Pending';

interface ExpectedMachineCategory {
  id: string;
  brand: string;
  model: string;
  type: string;
  quantity: number;
}

interface RentalAgreement {
  id: number;
  agreementNo: string;
  customerId?: string;
  customerNo: string;
  customerName: string;
  customerAddress?: string;
  serialNo: string;
  startDate: string;
  endDate: string | null;
  monthlyRent: number;
  outstanding: number;
  status: RentalStatus;
  rentalId?: string;
  purchaseRequestId?: number;
  purchaseRequestNumber?: string;
  expectedMachines?: number;
  addedMachines?: number;
  expectedMachineCategories?: ExpectedMachineCategory[];
}

interface MachineForAgreement {
  id: string;
  description: string;
  serialNumber: string;
  boxNumber: string;
  brandName?: string;
  modelName?: string;
  typeName?: string;
  scannedAt?: string;
  categoryIndex?: number;
}

// API response from GET /api/v1/rentals/by-number
interface RentalByNumberApiData {
  id: string;
  rentalId?: string;
  agreementNo: string;
  status: string;
  customerId?: string;
  customerName: string;
  customerAddress?: string;
  customerPhone?: string;
  customerEmail?: string;
  rentalStartDate: string;
  rentalEndDate: string | null; // null = open-ended
  monthlyRate: number;
  totalAmount: number;
  outstandingAmount: number;
  machines: { id: string; model: string; serialNumber: string; boxNumber?: string; description?: string }[];
  expectedMachines: number;
  addedMachines: number;
  expectedMachineCategories?: ExpectedMachineCategory[];
  purchaseRequestId?: string | null;
  purchaseRequestNumber?: string | null;
}

function mapBackendStatus(status: string): RentalStatus {
  const map: Record<string, RentalStatus> = {
    ACTIVE: 'Active',
    COMPLETED: 'Completed',
    CANCELLED: 'Cancelled',
    PENDING: 'Pending',
  };
  return map[status] ?? (status as RentalStatus);
}

function transformByNumberToAgreement(data: RentalByNumberApiData): RentalAgreement {
  const startDate =
    typeof data.rentalStartDate === 'string'
      ? data.rentalStartDate.split('T')[0]
      : new Date(data.rentalStartDate).toISOString().split('T')[0];
  const endDate =
    data.rentalEndDate == null || data.rentalEndDate === ''
      ? null
      : typeof data.rentalEndDate === 'string'
        ? data.rentalEndDate.split('T')[0]
        : new Date(data.rentalEndDate).toISOString().split('T')[0];
  return {
    id: 0,
    agreementNo: data.agreementNo,
    customerId: data.customerId,
    customerNo: '',
    customerName: data.customerName,
    customerAddress: data.customerAddress,
    serialNo: '',
    startDate,
    endDate: endDate ?? null,
    monthlyRent: data.monthlyRate ?? 0,
    outstanding: data.outstandingAmount ?? 0,
    status: mapBackendStatus(data.status),
    rentalId: data.rentalId,
    purchaseRequestNumber: data.purchaseRequestNumber ?? undefined,
    expectedMachines: data.expectedMachines,
    addedMachines: data.addedMachines,
    expectedMachineCategories: data.expectedMachineCategories,
  };
}

function transformApiMachinesToLocal(
  machines: RentalByNumberApiData['machines'],
  startCategoryIndex: number = 0
): MachineForAgreement[] {
  return machines.map((m, i) => ({
    id: m.id,
    description: m.description ?? `${m.serialNumber}${m.boxNumber ? ` · Box: ${m.boxNumber}` : ''}`,
    serialNumber: m.serialNumber,
    boxNumber: m.boxNumber ?? '',
    scannedAt: new Date().toISOString(),
    categoryIndex: startCategoryIndex,
  }));
}

// Minimal invoice shape for auto-generated invoice (from rental-agreement)
interface AutoGeneratedInvoiceItem {
  id: string;
  itemCode: string;
  description: string;
  serialNumber?: string;
  brand: string;
  model: string;
  type: string;
  numberOfMachines: number;
  monthlyRentPerMachine: number;
  subtotal: number;
}
interface AutoGeneratedInvoice {
  invoiceNumber: string;
  customerName: string;
  customerAddress: string;
  vatTinNic: string;
  invoiceDate: string;
  periodFrom: string;
  periodTo: string;
  items: AutoGeneratedInvoiceItem[];
  subtotal: number;
  vatAmount: number;
  totalAmount: number;
  status: 'issued';
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Get expected machine categories for an agreement. */
function getExpectedCategories(agreement: RentalAgreement | null): ExpectedMachineCategory[] {
  if (!agreement) return [];
  const cats = agreement.expectedMachineCategories;
  if (cats && cats.length > 0) return cats;
  const total = agreement.expectedMachines ?? 0;
  if (total <= 0) return [];
  return [{ id: 'default', brand: '', model: 'Machine', type: '', quantity: total }];
}

/** QR contains only serial number and box number. Extract from JSON or key: value text. */
function extractSerialAndBoxFromQR(decodedText: string): { serial: string; box: string } | null {
  const raw = (decodedText || '').trim();
  if (!raw) return null;

  try {
    const parsed = JSON.parse(raw);
    if (parsed && typeof parsed === 'object') {
      const serialCandidates = [
        parsed.serialNo,
        parsed.serialNO,
        parsed.serial,
        parsed.serialNumber,
        parsed.SerialNo,
        parsed.Serial,
        parsed.machineSerial,
        parsed.machineSerialNo,
      ].filter((v: unknown) => typeof v === 'string' && (v as string).trim().length > 0);
      const boxCandidates = [
        parsed.motorBoxNo,
        parsed.boxNo,
        parsed.boxNumber,
        parsed.MotorBoxNo,
        parsed.BoxNo,
        parsed.box,
      ].filter((v: unknown) => typeof v === 'string' && (v as string).trim().length > 0);
      const serial = serialCandidates.length > 0 ? (serialCandidates[0] as string).trim() : '';
      const box = boxCandidates.length > 0 ? (boxCandidates[0] as string).trim() : '';
      if (serial || box) return { serial, box: box || '' };
    }
  } catch {
    // not JSON, try key: value pattern
  }

  const serialMatch = raw.match(/serial\s*(no|number)?\s*[:\-=]\s*([A-Za-z0-9\-_/]+)/i);
  const boxMatch = raw.match(/(?:motor)?\s*box\s*(no|number)?\s*[:\-=]\s*([A-Za-z0-9\-_/]+)/i);
  const serial = serialMatch ? serialMatch[2].trim() : '';
  const box = boxMatch ? boxMatch[2].trim() : '';
  if (serial || box) return { serial, box: box || '' };

  return null;
}

function getUpdateInitialData(agreement: RentalAgreement | null): Record<string, unknown> {
  if (!agreement) return {};
  return {
    agreementNo: agreement.agreementNo,
    customerName: agreement.customerName,
    startDate: agreement.startDate,
    endDate: agreement.endDate || '',
    monthlyRent: agreement.monthlyRent,
    status: agreement.status,
  };
}

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

type ViewMode = 'menu' | 'details' | 'scan';

const MachineAssignPage: React.FC = () => {
  const [step, setStep] = useState<1 | 2>(1);
  const [isDarkMode, setIsDarkMode] = useState(true);
  const [mounted, setMounted] = useState(false);

  // Step 1: agreement input
  const [agreementNumberInput, setAgreementNumberInput] = useState('');
  const [lookupError, setLookupError] = useState<string | null>(null);
  const [lookupLoading, setLookupLoading] = useState(false);

  // Selected agreement + overall state (from API)
  const [selectedAgreement, setSelectedAgreement] = useState<RentalAgreement | null>(null);

  // Machine scanning state
  const [machinesForAgreement, setMachinesForAgreement] = useState<MachineForAgreement[]>([]);
  const [activeScanCategoryIndex, setActiveScanCategoryIndex] = useState<number | null>(null);
  const activeScanCategoryIndexRef = useRef<number | null>(null);
  const [scannerKey, setScannerKey] = useState(1);
  const [isSubmitting, setIsSubmitting] = useState(false);

  // Step 2 sub-view (menu / details / scan)
  const [viewMode, setViewMode] = useState<ViewMode>('menu');

  useEffect(() => {
    activeScanCategoryIndexRef.current = activeScanCategoryIndex;
  }, [activeScanCategoryIndex]);

  useEffect(() => {
    setMounted(true);
    const savedTheme = localStorage.getItem('theme');
    const systemPrefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
    const shouldBeDark = savedTheme === 'dark' || (savedTheme !== 'light' && systemPrefersDark);
    if (shouldBeDark) {
      document.documentElement.classList.add('dark');
      setIsDarkMode(true);
    } else {
      document.documentElement.classList.remove('dark');
      setIsDarkMode(false);
    }
  }, []);

  const toggleTheme = () => {
    const nextDark = !isDarkMode;
    setIsDarkMode(nextDark);
    if (nextDark) {
      document.documentElement.classList.add('dark');
      localStorage.setItem('theme', 'dark');
    } else {
      document.documentElement.classList.remove('dark');
      localStorage.setItem('theme', 'light');
    }
  };

  /** True when all expected categories have reached their required quantity. */
  const isAllCategoriesComplete = (): boolean => {
    if (!selectedAgreement) return false;
    const categories = getExpectedCategories(selectedAgreement);
    return categories.every((cat, i) => {
      const scanned = machinesForAgreement.filter((m) => m.categoryIndex === i).length;
      return scanned >= cat.quantity;
    });
  };

  const checkAndUpdateStatus = (currentMachines: MachineForAgreement[]) => {
    if (!selectedAgreement || selectedAgreement.status !== 'Pending') return;
    const added = currentMachines.length;
    setSelectedAgreement((prev) =>
      prev ? { ...prev, addedMachines: added } : null
    );
  };

  const handleRemoveMachineFromAgreement = (machineId: string) => {
    const updated = machinesForAgreement.filter((m) => m.id !== machineId);
    setMachinesForAgreement(updated);
    checkAndUpdateStatus(updated);
  };

  const handleOpenQRScanner = (categoryIndex: number) => {
    if (!selectedAgreement) return;
    const categories = getExpectedCategories(selectedAgreement);
    if (categoryIndex < 0 || categoryIndex >= categories.length) return;
    const cat = categories[categoryIndex];
    const scannedInCategory = machinesForAgreement.filter((m) => m.categoryIndex === categoryIndex).length;
    if (scannedInCategory >= cat.quantity) {
      alert(`All ${cat.quantity} machine(s) for this category have been added.`);
      return;
    }
    setActiveScanCategoryIndex(categoryIndex);
    setScannerKey((k) => k + 1);
  };

  /** QR code contains only serial number and box number. No brand/model/type. */
  const handleInlineQRScanSuccess = (decodedText: string) => {
    const categoryIndex = activeScanCategoryIndexRef.current;
    if (categoryIndex == null || !selectedAgreement) return;

    const extracted = extractSerialAndBoxFromQR(decodedText);
    if (!extracted || !extracted.serial.trim()) {
      alert('Invalid QR code: Could not read serial number. QR should contain serial number and box number only.');
      setScannerKey((k) => k + 1);
      return;
    }

    const serialNumber = extracted.serial.trim();
    const boxNumber = (extracted.box || '').trim();

    setMachinesForAgreement((prev) => {
      const isDuplicate = prev.some(
        (m) => m.serialNumber.toLowerCase() === serialNumber.toLowerCase()
      );
      if (isDuplicate) {
        setTimeout(() => {
          alert('This machine is already assigned to this agreement.');
          setScannerKey((k) => k + 1);
        }, 0);
        return prev;
      }
      const newMachine: MachineForAgreement = {
        id: Date.now().toString(),
        description: boxNumber ? `Serial: ${serialNumber} · Box: ${boxNumber}` : `Serial: ${serialNumber}`,
        serialNumber,
        boxNumber: boxNumber || '',
        scannedAt: new Date().toISOString(),
        categoryIndex,
      };
      const updated = [...prev, newMachine];
      checkAndUpdateStatus(updated);
      const categories = getExpectedCategories(selectedAgreement);
      const cat = categories[categoryIndex];
      const scannedInCat = updated.filter((m) => m.categoryIndex === categoryIndex).length;
      if (cat && scannedInCat >= cat.quantity) {
        setActiveScanCategoryIndex(null);
      }
      setTimeout(() => setScannerKey((k) => k + 1), 0);
      return updated;
    });
  };

  const handleContinueFromStep1 = async () => {
    const trimmed = agreementNumberInput.trim();
    if (!trimmed) {
      setLookupError('Please enter an agreement number.');
      return;
    }
    setLookupError(null);
    setLookupLoading(true);
    try {
      const res = await authFetch(
        `/api/v1/rentals/by-number?number=${encodeURIComponent(trimmed)}`
      );
      const json = await res.json();
      if (!res.ok) {
        const message =
          json?.message ?? (res.status === 404 ? 'Agreement not found.' : 'Failed to load agreement.');
        setLookupError(message);
        return;
      }
      const data = json?.data as RentalByNumberApiData | undefined;
      if (!data) {
        setLookupError('Invalid response from server.');
        return;
      }
      const agreement = transformByNumberToAgreement(data);
      const existingMachines = transformApiMachinesToLocal(data.machines ?? []);
      setMachinesForAgreement(existingMachines);
      setActiveScanCategoryIndex(null);
      setSelectedAgreement(agreement);
      setViewMode('menu');
      setStep(2);
    } catch (err) {
      setLookupError('Network error. Please try again.');
    } finally {
      setLookupLoading(false);
    }
  };

  const handleBackToStep1 = () => {
    setStep(1);
    setAgreementNumberInput('');
    setLookupError(null);
    setSelectedAgreement(null);
    setMachinesForAgreement([]);
    setActiveScanCategoryIndex(null);
    setViewMode('menu');
  };

  const handleCloseUpdate = () => {
    setSelectedAgreement(null);
    setMachinesForAgreement([]);
    setActiveScanCategoryIndex(null);
    setStep(1);
    setAgreementNumberInput('');
    setViewMode('menu');
  };

  const handleAgreementUpdate = async (data: Record<string, unknown>) => {
    if (!selectedAgreement) return;
    const rentalId = selectedAgreement.rentalId;
    if (!rentalId) {
      alert('Cannot update: rental ID missing.');
      return;
    }
    const wasPending = selectedAgreement.status === 'Pending';
    const categories = getExpectedCategories(selectedAgreement);
    const totalExpected = categories.reduce((sum, c) => sum + c.quantity, 0);

    if (wasPending && totalExpected > 0 && !isAllCategoriesComplete()) {
      alert(
        'Please complete machine assignment for all categories before submitting. Scan QR for each category until the required count is reached.'
      );
      return;
    }

    setIsSubmitting(true);
    try {
      const addedCount = machinesForAgreement.length;
      const newStatus =
        wasPending && totalExpected > 0 && addedCount >= totalExpected
          ? 'Active'
          : (data.status as RentalStatus) ?? selectedAgreement.status;

      const putBody = {
        status: newStatus,
        startDate: selectedAgreement.startDate || undefined,
        endDate: selectedAgreement.endDate || undefined,
        monthlyRent: selectedAgreement.monthlyRent,
        machines: machinesForAgreement.map((m) => ({
          serialNo: m.serialNumber,
          motorBoxNo: m.boxNumber || undefined,
        })),
      };

      const res = await authFetch(`/api/v1/rentals/${rentalId}`, {
        method: 'PUT',
        body: JSON.stringify(putBody),
      });
      const json = await res.json();

      if (!res.ok) {
        const message = json?.message ?? 'Failed to update rental agreement.';
        alert(message);
        return;
      }

      if (newStatus === 'Active' && wasPending && addedCount > 0) {
        const customerId = selectedAgreement.customerId;
        if (!customerId) {
          alert('Cannot create invoice: customer ID is missing. Please reload the agreement and try again.');
          return;
        }

        const monthlyRent = selectedAgreement.monthlyRent;
        const rentPerMachine = addedCount > 0 ? monthlyRent / addedCount : 0;
        const today = new Date().toISOString().split('T')[0];
        const periodFrom = selectedAgreement.startDate;
        const periodTo =
          selectedAgreement.endDate ||
          new Date(new Date(selectedAgreement.startDate).getTime() + 30 * 24 * 60 * 60 * 1000)
            .toISOString()
            .split('T')[0];

        const itemsByCategory = new Map<number, MachineForAgreement[]>();
        machinesForAgreement.forEach((m) => {
          const idx = m.categoryIndex ?? 0;
          if (!itemsByCategory.has(idx)) itemsByCategory.set(idx, []);
          itemsByCategory.get(idx)!.push(m);
        });
        const catList = getExpectedCategories(selectedAgreement);
        const invoiceItems: AutoGeneratedInvoiceItem[] = [];
        catList.forEach((cat, i) => {
          const machinesInCat = itemsByCategory.get(i) || [];
          const count = machinesInCat.length;
          if (count === 0) return;
          const desc = [cat.brand, cat.model, cat.type].filter(Boolean).join(' ') || 'Machine';
          const lineSubtotal = count * rentPerMachine;
          invoiceItems.push({
            id: String(invoiceItems.length + 1),
            itemCode: `212WG${String(invoiceItems.length + 1).padStart(5, '0')}`,
            description: desc.toUpperCase(),
            brand: cat.brand,
            model: cat.model,
            type: cat.type,
            numberOfMachines: count,
            monthlyRentPerMachine: rentPerMachine,
            subtotal: lineSubtotal,
          });
        });

        // Clear calculation: subtotal = sum of line subtotals, VAT 18%, grandTotal = subtotal + vatAmount
        const subtotalRaw = invoiceItems.reduce((s, it) => s + it.subtotal, 0);
        const subtotal = Math.round(subtotalRaw * 100) / 100;
        const VAT_RATE = 0.18;
        const vatAmount = Math.round(subtotal * VAT_RATE * 100) / 100;
        const totalAmount = Math.round((subtotal + vatAmount) * 100) / 100;

        // Build line items in API shape (matches invoice page)
        const lineItemsForApi = invoiceItems.map((item) => ({
          description: item.description,
          quantity: item.numberOfMachines,
          unitPrice: item.monthlyRentPerMachine,
          machineId: null as string | null,
          brand: item.brand,
          model: item.model,
          type: item.type,
          brandId: null as string | null,
          modelId: null as string | null,
          machineTypeId: null as string | null,
          itemCode: item.itemCode,
          serialNumber: undefined as string | undefined,
          vatRate: VAT_RATE,
        }));

        const invoicePayload = {
          customerId,
          rentalId,
          type: 'RENTAL',
          taxCategory: 'VAT',
          lineItems: lineItemsForApi,
          issueDate: today,
          dueDate: periodTo,
          subtotal,
          vatAmount,
          grandTotal: totalAmount,
        };

        const invoiceRes = await authFetch('/api/v1/invoices', {
          method: 'POST',
          body: JSON.stringify(invoicePayload),
        });
        const invoiceJson = await invoiceRes.json();

        if (!invoiceRes.ok) {
          const msg = invoiceJson?.message ?? invoiceJson?.errors ?? 'Failed to create invoice.';
          alert(`Rental updated, but invoice could not be created: ${typeof msg === 'string' ? msg : JSON.stringify(msg)}`);
          return;
        }

        const generatedInvoice: AutoGeneratedInvoice = {
          invoiceNumber: invoiceJson?.data?.invoiceNumber ?? `RA-${selectedAgreement.agreementNo}-${Date.now().toString().slice(-6)}`,
          customerName: selectedAgreement.customerName,
          customerAddress: selectedAgreement.customerAddress ?? '',
          vatTinNic: selectedAgreement.customerNo ?? '',
          invoiceDate: today,
          periodFrom,
          periodTo,
          items: invoiceItems,
          subtotal,
          vatAmount,
          totalAmount,
          status: 'issued',
        };
        try {
          localStorage.setItem('needletech_autoGeneratedInvoice', JSON.stringify(generatedInvoice));
        } catch {
          // ignore
        }
        alert(
          `Rental Agreement "${selectedAgreement.agreementNo}" is now Active. Invoice has been created. You can view it from the Invoice page.`
        );
      } else {
        alert(`Rental Agreement "${data.agreementNo}" updated successfully.`);
      }

      handleCloseUpdate();
    } finally {
      setIsSubmitting(false);
    }
  };

  // -------------------------------------------------------------------------
  // STEP 1: Agreement number entry
  // -------------------------------------------------------------------------
  if (step === 1) {
    return (
      <div className="min-h-screen w-full bg-gradient-to-br from-gray-100 via-gray-50 to-gray-100 dark:from-slate-900 dark:via-slate-800 dark:to-slate-900 transition-colors">
        {/* Header */}
        <div className="bg-white/90 dark:bg-slate-900/85 backdrop-blur-sm border-b border-gray-200 dark:border-slate-700/50 px-4 py-4">
          <div className="max-w-md mx-auto flex items-start justify-between gap-3">
            <div>
              <h1 className="text-xl font-bold text-gray-900 dark:text-white flex items-center gap-2">
                <Scan className="w-6 h-6 text-blue-600 dark:text-blue-400" />
                Machine Assignment
              </h1>
              <p className="text-sm text-gray-500 dark:text-slate-400 mt-1">
                Enter the rental agreement number to continue
              </p>
            </div>
            {mounted && (
              <button
                type="button"
                onClick={toggleTheme}
                className="p-2 rounded-xl bg-gray-100 dark:bg-slate-800 text-gray-600 dark:text-slate-300 hover:bg-gray-200 dark:hover:bg-slate-700 transition-colors"
                aria-label={isDarkMode ? 'Switch to light theme' : 'Switch to dark theme'}
              >
                {isDarkMode ? <Sun className="w-5 h-5" /> : <Moon className="w-5 h-5" />}
              </button>
            )}
          </div>
        </div>

        {/* Content */}
        <div className="px-4 py-8">
          <div className="max-w-md mx-auto space-y-4">
            <div className="bg-white dark:bg-slate-800/60 backdrop-blur-sm rounded-2xl border border-gray-200 dark:border-slate-700/60 p-6 space-y-4 shadow-sm dark:shadow-none">
              <label htmlFor="agreement-input" className="block text-sm font-medium text-gray-700 dark:text-slate-300">
                Agreement Number
              </label>
              <input
                id="agreement-input"
                type="text"
                autoComplete="off"
                value={agreementNumberInput}
                onChange={(e) => {
                  setAgreementNumberInput(e.target.value);
                  setLookupError(null);
                }}
                onKeyDown={(e) => e.key === 'Enter' && handleContinueFromStep1()}
                placeholder="e.g. RA24010006"
                className="w-full min-h-[52px] px-4 py-3 text-base border rounded-xl bg-gray-50 dark:bg-slate-900/50 text-gray-900 dark:text-white border-gray-300 dark:border-slate-600 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent placeholder:text-gray-400 dark:placeholder-slate-500"
                autoFocus
              />
              {lookupError && (
                <p className="text-sm text-red-600 dark:text-red-400 flex items-center gap-2" role="alert">
                  <span className="w-1.5 h-1.5 bg-red-500 dark:bg-red-400 rounded-full"></span>
                  {lookupError}
                </p>
              )}
              <p className="text-xs text-gray-500 dark:text-slate-500">
                Enter the rental agreement number (e.g. RA24010006)
              </p>
              <button
                type="button"
                onClick={() => void handleContinueFromStep1()}
                disabled={lookupLoading}
                className="w-full min-h-[52px] px-4 py-3 text-base font-semibold text-white bg-blue-600 rounded-xl hover:bg-blue-700 active:scale-[0.98] transition-all touch-manipulation flex items-center justify-center gap-2 disabled:opacity-70 disabled:cursor-not-allowed"
              >
                {lookupLoading ? (
                  <>
                    <Loader2 className="w-5 h-5 animate-spin" />
                    Looking up...
                  </>
                ) : (
                  <>
                    <CheckCircle2 className="w-5 h-5" />
                    Continue
                  </>
                )}
              </button>
            </div>
          </div>
        </div>
      </div>
    );
  }

  // -------------------------------------------------------------------------
  // STEP 2: Actions / Details / Scan
  // -------------------------------------------------------------------------
  if (!selectedAgreement) return null;

  const categories = getExpectedCategories(selectedAgreement);
  const totalExpected = categories.reduce((sum, c) => sum + c.quantity, 0);
  const totalScanned = machinesForAgreement.length;
  const allComplete = isAllCategoriesComplete();
  const latestMachine = machinesForAgreement[machinesForAgreement.length - 1];
  const previousMachines = machinesForAgreement.slice(0, -1).reverse();

  const currentCategoryIndex =
    activeScanCategoryIndex !== null
      ? activeScanCategoryIndex
      : categories.findIndex((cat, i) => {
          const scanned = machinesForAgreement.filter((m) => m.categoryIndex === i).length;
          return scanned < cat.quantity;
        });

  const canStartScanning =
    currentCategoryIndex >= 0 && currentCategoryIndex < categories.length;

  const handleStartScanFlow = () => {
    if (!canStartScanning) {
      alert('All planned machines are already scanned for this agreement.');
      return;
    }
    setViewMode('scan');
    handleOpenQRScanner(currentCategoryIndex);
  };

  // -------------------------------------------------------------------------
  // STEP 2 / VIEW: ACTION MENU (View details + Start scan)
  // -------------------------------------------------------------------------
  if (viewMode === 'menu') {
    const remaining = totalExpected - totalScanned;
    return (
      <div className="min-h-screen w-full bg-gradient-to-br from-gray-100 via-gray-50 to-gray-100 dark:from-slate-900 dark:via-slate-800 dark:to-slate-900 flex flex-col transition-colors">
        {/* Header */}
        <div className="bg-white/90 dark:bg-slate-900/85 backdrop-blur-sm border-b border-gray-200 dark:border-slate-700/60 px-4 py-3 flex items-center justify-between">
          <button
            type="button"
            onClick={handleBackToStep1}
            className="p-2 hover:bg-gray-100 dark:hover:bg-slate-800 rounded-lg transition-colors text-gray-700 dark:text-white"
            aria-label="Change agreement"
          >
            <ArrowLeft className="w-5 h-5" />
          </button>
          <div className="flex-1 text-center">
            <h1 className="text-lg font-bold text-gray-900 dark:text-white">Machine Assignment</h1>
            <p className="text-xs text-gray-500 dark:text-slate-400">
              Agreement #{selectedAgreement.agreementNo}
            </p>
          </div>
          {mounted ? (
            <button
              type="button"
              onClick={toggleTheme}
              className="p-2 rounded-xl bg-gray-100 dark:bg-slate-800 text-gray-600 dark:text-slate-300 hover:bg-gray-200 dark:hover:bg-slate-700 transition-colors"
              aria-label={isDarkMode ? 'Switch to light theme' : 'Switch to dark theme'}
            >
              {isDarkMode ? <Sun className="w-5 h-5" /> : <Moon className="w-5 h-5" />}
            </button>
          ) : (
            <div className="flex items-center gap-2">
              <Zap className="w-5 h-5 text-yellow-500 dark:text-yellow-400" />
              <Scan className="w-5 h-5 text-gray-600 dark:text-white" />
            </div>
          )}
        </div>

        {/* Content */}
        <div className="flex-1 px-4 py-6">
          <div className="max-w-xl mx-auto space-y-6">
            {/* Agreement summary */}
            <div className="bg-white dark:bg-slate-800/60 border border-gray-200 dark:border-slate-700/60 rounded-2xl p-5 space-y-3 shadow-sm dark:shadow-none">
              <div className="flex items-center justify-between gap-3">
                <div>
                  <p className="text-xs font-semibold text-gray-500 dark:text-slate-400 uppercase tracking-wide">
                    Agreement
                  </p>
                  <p className="text-base font-semibold text-gray-900 dark:text-white">
                    {selectedAgreement.agreementNo}
                  </p>
                </div>
                <span
                  className={`inline-flex items-center rounded-full px-3 py-1 text-xs font-medium ${
                    selectedAgreement.status === 'Pending'
                      ? 'bg-amber-500/10 text-amber-700 dark:text-amber-300 border border-amber-500/40'
                      : 'bg-emerald-500/10 text-emerald-700 dark:text-emerald-300 border border-emerald-500/40'
                  }`}
                >
                  {selectedAgreement.status}
                </span>
              </div>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-sm">
                <div>
                  <p className="text-gray-500 dark:text-slate-400 text-xs uppercase tracking-wide">Customer</p>
                  <p className="text-gray-900 dark:text-slate-100 font-medium truncate">
                    {selectedAgreement.customerName}
                  </p>
                </div>
                <div>
                  <p className="text-gray-500 dark:text-slate-400 text-xs uppercase tracking-wide">Period</p>
                  <p className="text-gray-900 dark:text-slate-100 font-medium">
                    {selectedAgreement.startDate} → {selectedAgreement.endDate ?? 'Ongoing'}
                  </p>
                </div>
                <div>
                  <p className="text-gray-500 dark:text-slate-400 text-xs uppercase tracking-wide">Monthly Rent</p>
                  <p className="text-gray-900 dark:text-slate-100 font-medium">
                    Rs. {selectedAgreement.monthlyRent.toLocaleString('en-LK')}
                  </p>
                </div>
                <div>
                  <p className="text-gray-500 dark:text-slate-400 text-xs uppercase tracking-wide">Machines</p>
                  <p className="text-gray-900 dark:text-slate-100 font-medium">
                    {totalExpected} planned · {totalScanned} scanned
                  </p>
                </div>
              </div>
            </div>

            {/* Actions */}
            <div className="bg-white dark:bg-slate-800/40 border border-gray-200 dark:border-slate-700/60 rounded-2xl p-5 space-y-4 shadow-sm dark:shadow-none">
              <p className="text-xs font-semibold text-gray-500 dark:text-slate-400 uppercase tracking-wide">
                What would you like to do?
              </p>

              <button
                type="button"
                onClick={() => setViewMode('details')}
                className="w-full min-h-[56px] px-4 py-3 rounded-xl border border-gray-300 dark:border-slate-600 bg-gray-50 dark:bg-slate-800/70 hover:bg-gray-100 dark:hover:bg-slate-700/80 transition-all flex items-center justify-between gap-3 text-left"
              >
                <div className="flex items-center gap-3">
                  <div className="w-9 h-9 rounded-xl bg-gray-200 dark:bg-slate-700/80 flex items-center justify-center">
                    <Info className="w-5 h-5 text-gray-600 dark:text-slate-200" />
                  </div>
                  <div className="text-left">
                    <p className="text-sm font-semibold text-gray-900 dark:text-white">View agreement details</p>
                    <p className="text-xs text-gray-500 dark:text-slate-400">
                      Summary, customer, duration and machine plan
                    </p>
                  </div>
                </div>
              </button>

              <button
                type="button"
                onClick={handleStartScanFlow}
                className="w-full min-h-[56px] px-4 py-3 rounded-xl bg-blue-600 hover:bg-blue-700 active:scale-[0.98] transition-all flex items-center justify-between gap-3 text-white font-semibold"
              >
                <div className="flex items-center gap-3">
                  <div className="w-9 h-9 rounded-xl bg-blue-500/30 flex items-center justify-center">
                    <Scan className="w-5 h-5" />
                  </div>
                  <div className="text-left">
                    <p className="text-sm">Start QR scanning</p>
                    <p className="text-xs text-blue-100/80">
                      Scan machines one by one to assign them
                    </p>
                  </div>
                </div>
                <div className="text-right text-xs">
                  <p className="text-blue-100">Remaining</p>
                  <p className="font-semibold">
                    {Math.max(remaining, 0)} / {totalExpected}
                  </p>
                </div>
              </button>

              <p className="text-[11px] text-gray-500 dark:text-slate-500">
                You can come back here any time to switch between viewing details and
                scanning without losing your progress.
              </p>
            </div>
          </div>
        </div>
      </div>
    );
  }

  // -------------------------------------------------------------------------
  // STEP 2 / VIEW: AGREEMENT DETAILS (with Back to actions)
  // -------------------------------------------------------------------------
  if (viewMode === 'details') {
    return (
      <div className="min-h-screen w-full bg-gradient-to-br from-gray-100 via-gray-50 to-gray-100 dark:from-slate-900 dark:via-slate-800 dark:to-slate-900 flex flex-col transition-colors">
        {/* Header */}
        <div className="bg-white/90 dark:bg-slate-900/85 backdrop-blur-sm border-b border-gray-200 dark:border-slate-700/60 px-4 py-3 flex items-center justify-between">
          <button
            type="button"
            onClick={() => setViewMode('menu')}
            className="p-2 hover:bg-gray-100 dark:hover:bg-slate-800 rounded-lg transition-colors flex items-center gap-1 text-xs text-gray-700 dark:text-slate-200"
          >
            <ArrowLeft className="w-4 h-4" />
            Back
          </button>
          <div className="flex-1 text-center">
            <h1 className="text-lg font-bold text-gray-900 dark:text-white">Agreement details</h1>
            <p className="text-xs text-gray-500 dark:text-slate-400">
              #{selectedAgreement.agreementNo}
            </p>
          </div>
          <div className="flex items-center gap-2">
            {mounted ? (
              <button
                type="button"
                onClick={toggleTheme}
                className="p-2 rounded-xl bg-gray-100 dark:bg-slate-800 text-gray-600 dark:text-slate-300 hover:bg-gray-200 dark:hover:bg-slate-700 transition-colors"
                aria-label={isDarkMode ? 'Switch to light theme' : 'Switch to dark theme'}
              >
                {isDarkMode ? <Sun className="w-5 h-5" /> : <Moon className="w-5 h-5" />}
              </button>
            ) : null}
            <button
              type="button"
              onClick={handleStartScanFlow}
              className="px-3 py-1.5 rounded-full bg-blue-600 hover:bg-blue-700 text-[11px] font-semibold text-white flex items-center gap-1"
            >
              <Scan className="w-3.5 h-3.5" />
              Start scan
            </button>
          </div>
        </div>

        {/* Content */}
        <div className="flex-1 px-4 py-6 overflow-y-auto">
          <div className="max-w-2xl mx-auto space-y-6">
            {/* High-level info */}
            <div className="bg-white dark:bg-slate-800/60 border border-gray-200 dark:border-slate-700/60 rounded-2xl p-5 space-y-3 shadow-sm dark:shadow-none">
              <div className="flex items-center justify-between gap-3">
                <div>
                  <p className="text-xs font-semibold text-gray-500 dark:text-slate-400 uppercase tracking-wide">
                    Customer
                  </p>
                  <p className="text-base font-semibold text-gray-900 dark:text-white">
                    {selectedAgreement.customerName}
                  </p>
                  {selectedAgreement.customerNo && (
                    <p className="text-xs text-gray-500 dark:text-slate-400 mt-0.5">
                      Customer #{selectedAgreement.customerNo}
                    </p>
                  )}
                </div>
                <span
                  className={`inline-flex items-center rounded-full px-3 py-1 text-xs font-medium ${
                    selectedAgreement.status === 'Pending'
                      ? 'bg-amber-500/10 text-amber-700 dark:text-amber-300 border border-amber-500/40'
                      : 'bg-emerald-500/10 text-emerald-700 dark:text-emerald-300 border border-emerald-500/40'
                  }`}
                >
                  {selectedAgreement.status}
                </span>
              </div>
              <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 text-xs sm:text-sm">
                <div>
                  <p className="text-gray-500 dark:text-slate-400 text-[11px] uppercase tracking-wide">Start</p>
                  <p className="text-gray-900 dark:text-slate-100 font-medium">
                    {selectedAgreement.startDate}
                  </p>
                </div>
                <div>
                  <p className="text-gray-500 dark:text-slate-400 text-[11px] uppercase tracking-wide">End</p>
                  <p className="text-gray-900 dark:text-slate-100 font-medium">
                    {selectedAgreement.endDate ?? 'Ongoing'}
                  </p>
                </div>
                <div>
                  <p className="text-gray-500 dark:text-slate-400 text-[11px] uppercase tracking-wide">Monthly Rent</p>
                  <p className="text-gray-900 dark:text-slate-100 font-medium">
                    Rs. {selectedAgreement.monthlyRent.toLocaleString('en-LK')}
                  </p>
                </div>
                <div>
                  <p className="text-gray-500 dark:text-slate-400 text-[11px] uppercase tracking-wide">Outstanding</p>
                  <p className="text-gray-900 dark:text-slate-100 font-medium">
                    Rs. {selectedAgreement.outstanding.toLocaleString('en-LK')}
                  </p>
                </div>
              </div>
            </div>

            {/* Machine plan */}
            <div className="bg-white dark:bg-slate-800/40 border border-gray-200 dark:border-slate-700/60 rounded-2xl p-5 space-y-3 shadow-sm dark:shadow-none">
              <div className="flex items-center justify-between gap-2">
                <p className="text-xs font-semibold text-gray-500 dark:text-slate-400 uppercase tracking-wide">
                  Machine plan
                </p>
                <p className="text-xs text-gray-500 dark:text-slate-400">
                  {totalScanned} of {totalExpected} machines scanned
                </p>
              </div>

              {categories.length === 0 ? (
                <p className="text-xs text-gray-500 dark:text-slate-500">
                  No planned machine categories defined for this agreement.
                </p>
              ) : (
                <div className="space-y-2">
                  {categories.map((cat, idx) => {
                    const scanned = machinesForAgreement.filter(
                      (m) => m.categoryIndex === idx
                    ).length;
                    const progress =
                      cat.quantity > 0 ? Math.min((scanned / cat.quantity) * 100, 100) : 0;
                    return (
                      <div
                        key={cat.id}
                        className="bg-gray-50 dark:bg-slate-900/40 border border-gray-200 dark:border-slate-700/60 rounded-xl px-4 py-3 space-y-2"
                      >
                        <div className="flex items-center justify-between gap-3">
                          <div>
                            <p className="text-sm font-semibold text-gray-900 dark:text-white">
                              {[cat.brand, cat.model].filter(Boolean).join(' ') || 'Machine'}
                            </p>
                            <p className="text-xs text-gray-500 dark:text-slate-400">
                              {cat.type || 'Category'} • {cat.quantity} machine(s)
                            </p>
                          </div>
                          <div className="text-right text-xs">
                            <p className="text-gray-500 dark:text-slate-400">Scanned</p>
                            <p className="font-semibold text-gray-900 dark:text-slate-100">
                              {scanned} / {cat.quantity}
                            </p>
                          </div>
                        </div>
                        <div className="w-full bg-gray-200 dark:bg-slate-800/80 rounded-full h-1.5 overflow-hidden">
                          <div
                            className={`h-1.5 rounded-full ${
                              scanned >= cat.quantity ? 'bg-emerald-500' : 'bg-blue-500'
                            }`}
                            style={{ width: `${progress}%` }}
                          />
                        </div>
                      </div>
                    );
                  })}
                </div>
              )}
            </div>

            {/* Current scans list */}
            <div className="bg-white dark:bg-slate-800/40 border border-gray-200 dark:border-slate-700/60 rounded-2xl p-5 space-y-3 shadow-sm dark:shadow-none">
              <div className="flex items-center justify-between gap-2">
                <p className="text-xs font-semibold text-gray-500 dark:text-slate-400 uppercase tracking-wide">
                  Assigned machines (scanned)
                </p>
                <p className="text-xs text-gray-500 dark:text-slate-400">
                  {totalScanned === 0
                    ? 'No scans yet'
                    : `${totalScanned} machine${totalScanned > 1 ? 's' : ''}`}
                </p>
              </div>
              {totalScanned === 0 ? (
                <div className="text-center py-6 text-xs text-gray-500 dark:text-slate-500">
                  Start scanning to see machines here.
                </div>
              ) : (
                <div className="space-y-2 max-h-60 overflow-y-auto">
                  {machinesForAgreement
                    .slice()
                    .reverse()
                    .map((machine) => (
                      <div
                        key={machine.id}
                        className="bg-gray-50 dark:bg-slate-900/40 border border-gray-200 dark:border-slate-700/60 rounded-xl px-4 py-3 flex items-center justify-between gap-3"
                      >
                        <div className="flex items-center gap-3 min-w-0">
                          <div className="w-8 h-8 rounded-lg bg-gray-200 dark:bg-slate-700/80 flex items-center justify-center">
                            <Scan className="w-4 h-4 text-gray-600 dark:text-slate-300" />
                          </div>
                          <div className="min-w-0">
                            <p className="text-sm font-semibold text-gray-900 dark:text-white truncate">
                              {machine.serialNumber}
                            </p>
                            <p className="text-xs text-gray-500 dark:text-slate-400">
                              Box {machine.boxNumber || '—'}
                            </p>
                          </div>
                        </div>
                      </div>
                    ))}
                </div>
              )}
            </div>
          </div>
        </div>
      </div>
    );
  }

  // -------------------------------------------------------------------------
  // STEP 2 / VIEW: SCANNING INTERFACE
  // -------------------------------------------------------------------------
  return (
    <div className="min-h-screen w-full bg-gradient-to-br from-gray-100 via-gray-50 to-gray-100 dark:from-slate-900 dark:via-slate-800 dark:to-slate-900 flex flex-col transition-colors">
      {/* Header */}
      <div className="bg-white/90 dark:bg-slate-900/85 backdrop-blur-sm border-b border-gray-200 dark:border-slate-700/60 px-4 py-3 flex items-center justify-between">
        <button
          type="button"
          onClick={() => setViewMode('menu')}
          className="p-2 hover:bg-gray-100 dark:hover:bg-slate-800 rounded-lg transition-colors text-gray-700 dark:text-white"
          aria-label="Back to actions"
        >
          <ArrowLeft className="w-5 h-5" />
        </button>
        <div className="flex-1 text-center">
          <h1 className="text-lg font-bold text-gray-900 dark:text-white">Scan inventory</h1>
          <p className="text-xs text-gray-500 dark:text-slate-400">
            Agreement #{selectedAgreement.agreementNo}
          </p>
        </div>
        <div className="flex items-center gap-2">
          {mounted && (
            <button
              type="button"
              onClick={toggleTheme}
              className="p-2 rounded-xl bg-gray-100 dark:bg-slate-800 text-gray-600 dark:text-slate-300 hover:bg-gray-200 dark:hover:bg-slate-700 transition-colors"
              aria-label={isDarkMode ? 'Switch to light theme' : 'Switch to dark theme'}
            >
              {isDarkMode ? <Sun className="w-5 h-5" /> : <Moon className="w-5 h-5" />}
            </button>
          )}
          <button
            type="button"
            onClick={() => setViewMode('details')}
            className="px-3 py-1.5 rounded-full bg-gray-200 dark:bg-slate-800 text-[11px] text-gray-700 dark:text-slate-100 border border-gray-300 dark:border-slate-700 flex items-center gap-1"
          >
            <Info className="w-3.5 h-3.5" />
            Details
          </button>
        </div>
      </div>

      {/* QR Scanner Section - Only show when actively scanning */}
      {activeScanCategoryIndex !== null && (
        <div
          className="relative flex-shrink-0 bg-black/60 backdrop-blur-sm"
          style={{ height: '45vh', minHeight: '280px' }}
        >
          <div className="absolute inset-0">
            <QRScannerComponent
              key={scannerKey}
              onScanSuccess={handleInlineQRScanSuccess}
              autoClose={false}
              showCloseButton={false}
              title=""
              subtitle=""
              embedded
            />
            <div className="absolute top-4 left-1/2 -translate-x-1/2 text-center">
              <p className="text-sm text-slate-200 dark:text-slate-300 font-medium">
                Align QR code within frame
              </p>
            </div>
            <div className="absolute bottom-4 left-1/2 -translate-x-1/2">
              <p className="text-xs text-slate-300 dark:text-slate-400">Auto-detecting...</p>
            </div>
          </div>
        </div>
      )}

      {/* Progress Section */}
      <div className="flex-1 bg-gray-50/80 dark:bg-slate-800/30 backdrop-blur-sm px-4 py-4 overflow-y-auto">
        <div className="max-w-2xl mx-auto space-y-4">
          {/* Scanning Progress Header */}
          <div className="flex items-center justify-between">
            <div>
              <h2 className="text-lg font-bold text-gray-900 dark:text-white">Scanning progress</h2>
              <p className="text-xs text-gray-500 dark:text-slate-400">
                Job ID: #{selectedAgreement.agreementNo}
              </p>
            </div>
            <div className="flex items-center gap-3 bg-white dark:bg-slate-800/50 rounded-xl px-4 py-2 border border-gray-200 dark:border-slate-700/50 shadow-sm dark:shadow-none">
              <div className="text-center">
                <div className="text-2xl font-bold text-gray-900 dark:text-white tabular-nums">
                  {totalScanned}
                </div>
                <div className="text-xs text-gray-500 dark:text-slate-400">Scanned</div>
              </div>
              <div className="w-px h-8 bg-gray-300 dark:bg-slate-700" />
              <div className="text-center">
                <div className="text-2xl font-bold text-gray-900 dark:text-white tabular-nums">
                  {totalExpected}
                </div>
                <div className="text-xs text-gray-500 dark:text-slate-400">Total</div>
              </div>
            </div>
          </div>

          {/* Progress Bar */}
          <div className="space-y-2">
            <div className="w-full bg-gray-200 dark:bg-slate-700/50 rounded-full h-1.5 overflow-hidden">
              <div
                className={`h-1.5 rounded-full transition-all duration-500 ${
                  allComplete ? 'bg-green-500' : 'bg-blue-500'
                }`}
                style={{
                  width: `${totalExpected > 0 ? (totalScanned / totalExpected) * 100 : 0}%`,
                }}
              />
            </div>
          </div>

          {/* Latest Scan */}
          {latestMachine && (
            <div className="bg-gradient-to-r from-emerald-100 to-teal-100 dark:from-emerald-900/30 dark:to-teal-900/30 backdrop-blur-sm border border-emerald-300 dark:border-emerald-700/50 rounded-xl p-4">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-3 flex-1 min-w-0">
                  <div className="flex-shrink-0 w-10 h-10 bg-emerald-500 rounded-full flex items-center justify-center">
                    <CheckCircle2 className="w-6 h-6 text-white" />
                  </div>
                  <div className="flex-1 min-w-0">
                    <p className="text-base font-bold text-emerald-800 dark:text-emerald-300 truncate">
                      {latestMachine.serialNumber}
                    </p>
                    <p className="text-sm text-emerald-600 dark:text-emerald-400/80">
                      Box {latestMachine.boxNumber || '—'} • Added
                    </p>
                  </div>
                </div>
                <button
                  type="button"
                  onClick={() => handleRemoveMachineFromAgreement(latestMachine.id)}
                  className="flex-shrink-0 p-2 hover:bg-gray-200 dark:hover:bg-slate-800/50 rounded-lg transition-colors text-gray-600 dark:text-slate-400"
                  aria-label="Undo last scan"
                >
                  <RotateCcw className="w-5 h-5" />
                </button>
              </div>
            </div>
          )}

          {/* Previous Scans */}
          {previousMachines.length > 0 && (
            <div className="space-y-2">
              <h3 className="text-xs font-semibold text-gray-500 dark:text-slate-400 uppercase tracking-wider">
                Previous scans
              </h3>
              <div className="space-y-2 max-h-40 overflow-y-auto">
                {previousMachines.map((machine) => (
                  <div
                    key={machine.id}
                    className="bg-white dark:bg-slate-800/30 backdrop-blur-sm border border-gray-200 dark:border-slate-700/50 rounded-lg p-3 flex items-center justify-between shadow-sm dark:shadow-none"
                  >
                    <div className="flex items-center gap-3 flex-1 min-w-0">
                      <div className="flex-shrink-0 w-8 h-8 bg-gray-200 dark:bg-slate-700/50 rounded-lg flex items-center justify-center">
                        <Scan className="w-4 h-4 text-gray-500 dark:text-slate-400" />
                      </div>
                      <div className="flex-1 min-w-0">
                        <p className="text-sm font-semibold text-gray-900 dark:text-white truncate">
                          {machine.serialNumber}
                        </p>
                        <p className="text-xs text-gray-500 dark:text-slate-400">
                          Box {machine.boxNumber || '—'}
                        </p>
                      </div>
                    </div>
                    <button
                      type="button"
                      onClick={() => handleRemoveMachineFromAgreement(machine.id)}
                      className="flex-shrink-0 p-2 hover:bg-gray-200 dark:hover:bg-slate-700/50 rounded-lg transition-colors text-gray-500 dark:text-slate-400"
                      aria-label="Delete scan"
                    >
                      <Trash2 className="w-4 h-4" />
                    </button>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Start/Resume Scanning Button */}
          {!allComplete && canStartScanning && activeScanCategoryIndex === null && (
            <button
              type="button"
              onClick={handleStartScanFlow}
              className="w-full min-h-[56px] px-6 py-3 text-base font-semibold text-white bg-blue-600 rounded-xl hover:bg-blue-700 active:scale-[0.98] transition-all touch-manipulation flex items-center justify-center gap-2"
            >
              <Scan className="w-5 h-5" />
              {totalScanned === 0 ? 'Start scanning' : 'Resume scanning'}
            </button>
          )}

          {/* Done Scanning Button */}
          {(allComplete || totalScanned > 0) && activeScanCategoryIndex === null && (
            <button
              type="button"
              onClick={async () => {
                if (!allComplete) {
                  const confirmFinish = window.confirm(
                    `You've scanned ${totalScanned} of ${totalExpected} machines. Are you sure you want to finish?`
                  );
                  if (!confirmFinish) return;
                }

                setIsSubmitting(true);
                try {
                  const data = getUpdateInitialData(selectedAgreement);
                  await handleAgreementUpdate({ ...data, status: 'Active' });
                } finally {
                  setIsSubmitting(false);
                }
              }}
              disabled={isSubmitting}
              className="w-full min-h-[56px] px-6 py-3 text-base font-semibold text-white bg-emerald-600 rounded-xl hover:bg-emerald-700 active:scale-[0.98] transition-all touch-manipulation flex items-center justify-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed"
            >
              <CheckCircle2 className="w-5 h-5" />
              {isSubmitting ? 'Processing...' : 'Done scanning & create invoice'}
            </button>
          )}

          {totalScanned === 0 && (
            <div className="text-center py-8 px-4">
              <Scan className="w-12 h-12 text-gray-400 dark:text-slate-600 mx-auto mb-3" />
              <p className="text-sm font-medium text-gray-500 dark:text-slate-400">
                No machines scanned yet
              </p>
              <p className="text-xs text-gray-500 dark:text-slate-500 mt-1">
                Tap “Start scanning” to begin assigning machines to this agreement.
              </p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default MachineAssignPage;