import { NextRequest } from 'next/server';
import { getDatabase } from '@/lib/mongodb';
import { successResponse, errorResponse, paginatedResponse, validationErrorResponse } from '@/lib/api-response';
import { parseQueryParams, buildPaginationMeta, sanitizeObject } from '@/lib/utils';
import { withAuth } from '@/lib/auth';
import { ObjectId } from 'mongodb';

export const GET = withAuth(async (request: NextRequest) => {
  try {
    const db = await getDatabase();
    const searchParams = request.nextUrl.searchParams;
    const { page, limit, sortBy, sortOrder, search } = parseQueryParams(searchParams);
    
    const brandFilter = searchParams.get('brand');
    const statusFilter = searchParams.get('status');
    const categoryFilter = searchParams.get('category');
    
    const filter: any = {};
    
    if (search) {
      filter.$or = [
        { serialNumber: { $regex: search, $options: 'i' } },
        { model: { $regex: search, $options: 'i' } },
        { boxNumber: { $regex: search, $options: 'i' } },
        { 'qrCode.value': { $regex: search, $options: 'i' } },
      ];
    }
    
    if (brandFilter) filter.brand = brandFilter;
    if (statusFilter) filter.status = statusFilter;
    if (categoryFilter) filter.category = categoryFilter;
    
    const totalItems = await db.collection('machines').countDocuments(filter);
    const skip = (page - 1) * limit;
    const sortObj: Record<string, 1 | -1> = { [sortBy]: sortOrder as 1 | -1 };
    
    const machines = await db
      .collection('machines')
      .find(filter)
      .sort(sortObj)
      .skip(skip)
      .limit(limit)
      .toArray();
    
    const sanitizedMachines = machines.map(machine => sanitizeObject(machine));
    
    const pagination = buildPaginationMeta(totalItems, page, limit);
    
    return paginatedResponse(
      sanitizedMachines,
      pagination,
      'Machines retrieved successfully',
      { sortBy, sortOrder: sortOrder === 1 ? 'asc' : 'desc' },
      search || undefined,
      {
        ...(brandFilter && { brand: brandFilter }),
        ...(statusFilter && { status: statusFilter }),
        ...(categoryFilter && { category: categoryFilter }),
      }
    );
  } catch (error: any) {
    console.error('Error fetching machines:', error);
    return errorResponse('Failed to retrieve machines', 500);
  }
});

export const POST = withAuth(async (request: NextRequest) => {
  try {
    const body = await request.json();
    const { brand, model, category, serialNumber, boxNumber, photos, specs, currentLocation } = body;
    
    if (!brand || !serialNumber) {
      return validationErrorResponse('Missing required fields', {
        brand: !brand ? ['Brand is required'] : [],
        serialNumber: !serialNumber ? ['Serial number is required'] : [],
      });
    }
    
    const db = await getDatabase();
    
    // Check if serial number already exists
    const existingMachine = await db.collection('machines').findOne({ serialNumber });
    if (existingMachine) {
      return validationErrorResponse('Serial number already exists', {
        serialNumber: ['Serial number already exists'],
      });
    }
    
    const now = new Date();
    const qrCodeValue = `MCH-${brand}-${serialNumber}`;
    
    const newMachine = {
      brand,
      model: model || '',
      category: category || '',
      serialNumber,
      boxNumber: boxNumber || '',
      qrCode: {
        value: qrCodeValue,
        imageUrl: '', // Will be generated by QR service
      },
      photos: photos || [],
      specs: specs || {},
      status: 'AVAILABLE',
      statusHistory: [
        {
          status: 'AVAILABLE',
          changedAt: now,
          changedByUserId: null, // TODO: Get from auth context
          note: 'Initial registration',
        },
      ],
      currentLocation: currentLocation || {
        type: 'WAREHOUSE',
        name: 'Main Warehouse',
        address: '',
      },
      lifecycle: {
        onboardedAt: now,
        onboardedByUserId: null, // TODO: Get from auth context
        lastRentalId: null,
        totalRentalDays: 0,
      },
      createdAt: now,
      updatedAt: now,
    };
    
    const result = await db.collection('machines').insertOne(newMachine);
    const createdMachine = await db.collection('machines').findOne({ _id: result.insertedId });
    
    return successResponse(sanitizeObject(createdMachine), 'Machine created successfully', 201);
  } catch (error: any) {
    console.error('Error creating machine:', error);
    return errorResponse('Failed to create machine', 500);
  }
});
